--------------------------------------------------
Identified names are: winston churchill
--------------------------------------------------
--------------------------------------------------
Query string is: winston churchill if you are going through hell, keep going
--------------------------------------------------


--------------------------------------------------
Query string is: winston churchill winston churchill
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 429: Too Many Requests
http://cancercurefinder.com/, 0.7, ['you', 'are', 'going', 'through', 'hell,', 'keep', 'winston'], 'if you are going through hell, keep going. winston churchill ', [272, 273, 274, 275, 276, 277, 280], False, False, False, True
https://quotefancy.com/quote/722/Winston-Churchill-If-you-are-going-through-hell-keep-going, 0.7, ['you', 'are', 'going', 'through', 'hell,', 'keep', 'winston'], 'if you are going through hell, keep going. winston churchill ', [1321, 1322, 1323, 1324, 1325, 1326, 1330], False, False, False, True
https://www.azquotes.com/quote/518250, 0.6, ['going', 'through', 'hell,', 'keep', 'going.', 'winston'], 'if you are going through hell, keep going. winston churchill ', [1044, 1045, 1046, 1047, 1048, 1050], False, False, False, True
https://www.brainyquote.com/quotes/winston_churchill_103788, 0.6, ['going', 'through', 'hell,', 'keep', 'going.', 'winston'], 'if you are going through hell, keep going. winston churchill ', [1038, 1039, 1040, 1041, 1042, 1044], False, False, False, True
http://thinkexist.com/quotation/if_you_are_going_through_hell-keep_going/219081.html, 0.6, ['you', 'are', 'going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [1080, 1081, 1082, 1083, 1084, 1085], False, False, False, True
https://www.goodreads.com/author/quotes/2834066.Winston_Churchill, 0.6, ['you', 'are', 'going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [2567, 2568, 2569, 2570, 2571, 2572], False, False, False, True
https://www.goodreads.com/author/quotes/14033.Winston_S_Churchill, 0.6, ['you', 'are', 'going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [2046, 2047, 2048, 2049, 2050, 2051], False, False, False, True
https://www.goodreads.com/quotes/6221-if-you-are-going-through-hell-keep-going, 0.6, ['you', 'are', 'going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [1778, 1779, 1780, 1781, 1782, 1783], False, False, False, True
https://www.backofthenorthwind.com/if-youre-going-through-hell-keep-going-winston-churchill/, 0.6, ['going', 'through', 'hell,', 'keep', 'winston', 'churchill'], 'if you are going through hell, keep going. winston churchill ', [1929, 1930, 1931, 1932, 1934, 1935], False, False, False, True
https://gunroswell.wordpress.com/tag/if-youre-going-through-hell-keep-going-winston-churchill/, 0.5, ['going', 'through', 'hell,', 'keep', 'winston'], 'if you are going through hell, keep going. winston churchill ', [1179, 1180, 1181, 1182, 1184], False, False, False, True
https://www.fearlessmotivation.com/2018/07/03/winston-churchill-quotes/, 0.5, ['you', 'are', 'going', 'through', 'hell,'], 'if you are going through hell, keep going. winston churchill ', [4703, 4704, 4705, 4706, 4707], False, False, False, True
http://www.answers.com/Q/When_did_Winston_Churchill_say_if_you\'re_going_through_hell_keep_going, 0.5, ['you', 'are', 'going', 'through', 'keep'], 'if you are going through hell, keep going. winston churchill ', [6705, 6706, 6707, 6708, 6722], False, False, False, True
https://www.hackensackmeridianhealth.org/health-ambassadors/hmhe_admin/2019/05/14/if-you-are-going-through-hell-keep-going/, 0.5, ['you', 'are', 'going', 'through', 'keep'], 'if you are going through hell, keep going. winston churchill ', [1209, 1210, 1211, 1212, 1214], False, False, False, True
https://www.saturdayeveningpost.com/did-winston-churchill-really-say-that-answers/, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [1030, 1031, 1032, 1033], False, False, False, True
https://quoteinvestigator.com/2014/09/14/keep-going/, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [7681, 7682, 7683, 7684], False, False, False, True
https://www.goalcast.com/2017/06/20/top-24-winston-churchill-quotes-to-inspire-you-to-never-surrender/, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [7126, 7127, 7128, 7129], False, False, False, True
https://www.brainyquote.com/authors/winston_churchill, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [1803, 1804, 1805, 1806], False, False, False, True
https://www.azquotes.com/author/2886-Winston_Churchill, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [6769, 6770, 6771, 6772], False, False, False, True
https://www.youtube.com/watch?v=uuxMZL6ieWM, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [3041, 3042, 3043, 3044], False, False, False, True
https://www.forbes.com/sites/geoffloftus/2012/05/09/if-youre-going-through-hell-keep-going-winston-churchill/, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [10787, 10788, 10789, 10790], False, False, False, True
https://www.sawdustcityllc.com/if-youre-going-through-hell-keep-going-winston-churchill/, 0.4, ['going', 'through', 'hell,', 'keep'], 'if you are going through hell, keep going. winston churchill ', [4825, 4826, 4827, 4828], False, False, False, True
https://www.uncommongoods.com/product/keep-going-paperweight, 0.4, ['going', 'through', 'winston', 'churchill'], 'if you are going through hell, keep going. winston churchill ', [3986, 3987, 3991, 3992], False, False, False, True
https://www.youtube.com/watch?v=VJnUgD5diaU, 0.3, ['going', 'through', 'hell,'], 'if you are going through hell, keep going. winston churchill ', [4414, 4415, 4416], False, False, False, True
https://psychicreiki.com/when-going-through-hell-keep-going-winston-churchill.html, 0.3, ['going', 'through', 'hell,'], 'if you are going through hell, keep going. winston churchill ', [2179, 2180, 2181], False, False, False, True
https://me.me/i/if-youre-going-through-hell-keep-going-winston-churchill-2836369, 0.3, ['going', 'through', 'hell,'], 'if you are going through hell, keep going. winston churchill ', [6990, 6991, 7006], True, False, False, True
https://www.gov.uk/government/history/past-prime-ministers/winston-churchill, 0.2, ['if', 'you'], 'if you are going through hell, keep going. winston churchill ', [2011, 2012], False, False, False, True
https://www.businessinsider.com/elon-musk-on-winston-churchill-hell-quote-2015-1, 0.2, ['you', 'are'], 'if you are going through hell, keep going. winston churchill ', [7993, 7994], False, False, False, True
https://www.nationalchurchillmuseum.org/winston-churchills-speeches.html, 0.2, ['are', 'going'], 'if you are going through hell, keep going. winston churchill ', [1260, 1261], False, False, False, True
https://www.biography.com/political-figure/winston-churchill, 0.2, ['winston', 'churchill'], 'if you are going through hell, keep going. winston churchill ', [9191, 9192], False, True, False, True
https://winstonchurchill.org/visit/churchill-war-rooms/, 0.2, ['if', 'are'], 'if you are going through hell, keep going. winston churchill ', [721, 723], False, False, False, True
https://www.notablebiographies.com/Ch-Co/Churchill-Winston.html, 0.2, ['if', 'you'], 'if you are going through hell, keep going. winston churchill ', [802, 804], False, False, False, True
https://www.history.com/news/winston-churchills-world-war-disaster, 0.2, ['winston', 'churchill'], 'if you are going through hell, keep going. winston churchill ', [4810, 4811], False, True, False, True
https://www.englishforums.com/English/IfYoureGoingThroughHellKeepGoing/zdjrb/post.htm, 0.2, ['you', 'are'], 'if you are going through hell, keep going. winston churchill ', [1392, 1393], False, False, False, True
https://www.thoughtco.com/winston-churchills-iron-curtain-speech-1779492, 0.2, ['winston', 'churchill'], 'if you are going through hell, keep going. winston churchill ', [10501, 10502], False, False, False, True
https://www.quotesandsayings.com/authors/winston-churchill/, 0.2, ['winston', 'churchill'], 'if you are going through hell, keep going. winston churchill ', [2409, 2410], False, False, False, True
https://www.reddit.com/r/QuotesPorn/comments/7j98cr/if_youre_going_through_hell_keep_going_winston/, 0.2, ['you', 'are'], 'if you are going through hell, keep going. winston churchill ', [7830, 7831], False, False, False, True
https://me.me/i/if-youre-going-through-hell-keep-going-winston-churchill-4318917, 0.2, ['going', 'through'], 'if you are going through hell, keep going. winston churchill ', [5461, 5462], True, False, False, True
https://www.amazon.com/Going-Through-Hell-Winston-Churchill/dp/B000MXVBGC, 0.2, ['you', 'are'], 'if you are going through hell, keep going. winston churchill ', [30379, 30380], False, False, False, True
https://www.amazon.com/Through-Keep-Winston-Churchill-premium/dp/B00BU9D8UY, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.snopes.com/fact-check/churchill-on-islam/, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, True, False, True
https://www.ducksters.com/biography/winston_churchill.php, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.cheatsheet.com/entertainment/princess-diana-related-winston-churchill.html/, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.brainyquote.com/quotes/winston_churchill_124653, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.biografiasyvidas.com/biografia/c/churchill.htm, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.history.com/topics/british-history/winston-churchill, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, True, False, True
https://en.wikipedia.org/wiki/Winston_Churchill_(1940%E2%80%932010), 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://winstonchurchill.org/, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://simple.wikipedia.org/wiki/Winston_Churchill, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.telegraph.co.uk/news/winston-churchill/11366880/Winston-Churchills-10-most-important-speeches.html, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://commons.wikimedia.org/wiki/Winston_Churchill, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.telegraph.co.uk/tv/0/father-accused-soviet-spy-bugging-winston-churchills-hearing/, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.britannica.com/biography/Winston-Churchill, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.imdb.com/name/nm0161476/, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://duckduckgo.com/y.js?u3=https%3A%2F%2Fr.search.yahoo.com%2Fcbclk%2FdWU9QzJCMzIyQ0VCNzQ5NDg4RSZ1dD0xNTU4MDI3MTMwODUwJnVvPTc1OTM1MTI3MTk2ODI0Jmx0PTImcz0yJmVzPVIyY1ZVNGNHUFM4akJNcE1LclNpazhOQTBIMXllcFVJU0p3VVZLemF4bTlwMXVfdjV3LS0%2D%2FRV%3D2%2FRE%3D1558055931%2FRO%3D10%2FRU%3Dhttps%253a%252f%252fwww.bing.com%252faclick%253fld%253de3NMvyWfw2UeZLQFxJjsOkxjVUCUwQTG_BLGneghlvuLAmNdmYPDy5UA6JamJiWjg2xGX7qFu0QPQtFpDcRli2tQka_BStLv5Wk13DQMCXWMnZsgjm1Nro1dvCcrjmgkyISnwU6XY6CTG01eImY3mcr7MhsONUajgwDFBJkHeBXrMIHvIU%2526u%253daHR0cHMlM2ElMmYlMmZ3d3cudWRlbXkuY29tJTJmbGVhZGVyc2hpcC1pbnNpZGUtdGhlLW1pbmQtb2Ytd2luc3Rvbi1jaHVyY2hpbGwlMmYlM2Z1dG1fc291cmNlJTNkYmluZyUyNnV0bV9tZWRpdW0lM2R1ZGVteWFkcyUyNnV0bV9jYW1wYWlnbiUzZE5FVy1CRy1QUk9TLVBST0YtVVMtRFNBLUVOLUVOR18uX2NpX18uX3NsX0VOR18uX3ZpX1BST0ZfLl9zZF9BbGxfLl9sYV9FTl8uXyUyNnV0bV9jb250ZW50JTNkZGVhbDQ1ODQlMjZ1dG1fdGVybSUzZF8uX2FnXzEyMTQ5NjA2NjExNTIwNTVfLl9hZF8lN2JjcmVhdGl2ZSU3ZF8uX2t3X1BST0YlMjUyMGV2ZXJ5dGhpbmdfZWxzZV9sb3dfLl9kZV9jXy5fZG1fJTdiZGV2aWNlbW9kZWwlN2RfLl9wbF8lN2JwbGFjZW1lbnQlN2RfLl90aV9kYXQtMjMyNzczNDgzNTUzMzYxNyUzYWxvYy0xOTBfLl9saV81MTYzOV8uX3BkXyU3YnByb2R1Y3RfaWQlN2RfLl8lMjZtYXRjaHR5cGUlM2RiJTI2bXNjbGtpZCUzZDJlMGYxYzA1ZThlMzE5ZjE5NjdmNDBkODczOThkZjgx%2526rlid%253d2e0f1c05e8e319f1967f40d87398df81%2FRK%3D2%2FRS%3D29n0HBcPuon1JtcMjwKL2cfuJ34%2D&ad_provider=yhs&vqd=3-258163315509931341964239555229516497711-330797399354749989314737514887632637959, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.imdb.com/title/tt2674454/, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://duckduckgo.com/y.js?u3=https%3A%2F%2Fr.search.yahoo.com%2Fcbclk%2FdWU9QzJCMzIyQ0VCNzQ5NDg4RSZ1dD0xNTU4MDI3MTMwODUwJnVvPTc4NTQ2NDYyNDE2NjYyJmx0PTImcz0yJmVzPWEyd1JfUUlHUFM5bHZ0bmtJT0J6Ny5hcDl5dVlPRlJpVzh3NmZtNk1xQ3FJd1UuZg%2D%2D%2FRV%3D2%2FRE%3D1558055931%2FRO%3D10%2FRU%3Dhttps%253a%252f%252fwww.bing.com%252faclick%253fld%253de39tD4tmbf5%2DkoRcujwS3C9TVUCUyP2yMNHgjWLWpftWKP28wCKtIxq88BSp0tpYRTUjwqRI_idK_1T_istiFSqArA3E8zUXrLYTJpdGtt71WIdarr2THPq4SijH0QoB1D8xOekwM_A4bnYQ_K0Rcr2HfzFftervXnjt5lf8CL1Qd1Hq0Q%2526u%253daHR0cHMlM2ElMmYlMmZ3d3cuYnJlY2tzLmNvbSUyZnByb2R1Y3QlMmZ3aW5zdG9uLWNodXJjaGlsbC1hc3RlciUzZnAlM2QwNzAwNjkxJTI2bXNjbGtpZCUzZDNjNWI4ZWUyNTI3YTEzODFiNWQ4ZDIzZmM5MDE2MmIyJTI2dXRtX3NvdXJjZSUzZGJpbmclMjZ1dG1fbWVkaXVtJTNkY3BjJTI2dXRtX2NhbXBhaWduJTNkRFNBJTI1MjAtJTI1MjBDYXRlZ29yaWVzJTI2dXRtX3Rlcm0lM2RicmVja3MlMjZ1dG1fY29udGVudCUzZEFsbCUyNTIwV2VicGFnZXM%2526rlid%253d3c5b8ee2527a1381b5d8d23fc90162b2%2FRK%3D2%2FRS%3DzYqbzU3ZdUuLDTFZmglqpyLVY_g%2D&ad_provider=yhs&vqd=3-327588056395953515914060090986121480445-330797399354749989314737514887632637959, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://independenttravelcats.com/churchill-in-london-a-guide-winston-churchill-sites-in-london-england/, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://www.sanjuan.edu/Churchill, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
https://en.wikipedia.org/wiki/Winston_Churchill, 0.0, [], 'if you are going through hell, keep going. winston churchill ', [], False, False, False, True
