--------------------------------------------------
Identified names are: ruth bader ginsburg
--------------------------------------------------
--------------------------------------------------
Query string is: ruth bader ginsburg f ere was one decision i 0 ld overrule, it would be iti ens united
--------------------------------------------------


--------------------------------------------------
Query string is: ruth bader ginsburg i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us
--------------------------------------------------


--------------------------------------------------
Query string is: ruth bader ginsburg supreme court justice ruth bader ginsburg
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
http://www.betterworld.net/quotes/CitizensUnited-quotes.htm, 0.5957446808510638, ['was', 'one', 'decision', 'i', 'overrule,', 'it', 'would', 'be', 'united.', 'i', 'think', 'the', 'that', 'we', 'have', 'all', 'the', 'that', 'money', 'buy', 'strays', 'so', 'far', 'from', 'our', 'democracy', 'is', 'supposed'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [980, 981, 982, 983, 985, 986, 988, 989, 991, 992, 993, 994, 996, 997, 999, 1000, 1001, 1003, 1004, 1006, 1007, 1008, 1010, 1011, 1013, 1014, 1015, 1016], False, False, False, True
https://www.biography.com/law-figure/ruth-bader-ginsburg, 0.574468085106383, ['was', 'one', 'decision', 'i', 'overrule,', 'it', 'would', 'be', 'i', 'think', 'the', 'that', 'we', 'have', 'all', 'the', 'that', 'money', 'buy', 'strays', 'so', 'far', 'from', 'our', 'democracy', 'is', 'supposed'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [3249, 3250, 3251, 3252, 3254, 3255, 3256, 3257, 3260, 3261, 3262, 3264, 3265, 3266, 3267, 3268, 3270, 3271, 3273, 3274, 3275, 3276, 3277, 3279, 3280, 3281, 3282], False, True, False, True
https://www.foxnews.com/us/supreme-court-justice-ruth-bader-ginsburg-fractures-3-ribs-in-fall, 0.14893617021276595, ['from', 'to', 'court', 'justice', 'ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [2527, 2571, 2574, 2575, 2576, 2577, 2578], False, False, False, True
https://www.nytimes.com/2019/02/15/us/politics/ruth-ginsburg-supreme-court.html, 0.1276595744680851, ['to', 'supreme', 'court', 'ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [6797, 6861, 6862, 6864, 6865, 6866], False, False, False, True
http://time.com/ruth-bader-ginsburg-supreme-court/, 0.1276595744680851, ['supreme', 'court', 'justice', 'ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [9431, 9432, 9444, 9487, 9488, 9489], False, False, False, True
https://www.cnbc.com/2018/12/21/supreme-court-justice-ruth-bader-ginsburg-85-reportedly-undergoes-lung-procedure-.html, 0.1276595744680851, ['to', 'court', 'justice', 'ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [8618, 8642, 8643, 8644, 8645, 8646], False, False, False, True
https://www.usatoday.com/story/news/politics/2019/02/15/ruth-bader-ginsburg-returns-supreme-court-cancer-scare/2859678002/, 0.1276595744680851, ['supreme', 'court', 'justice', 'ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [13226, 13239, 13240, 13263, 13264, 13265], False, False, False, True
https://www.washingtonpost.com/history/2018/10/25/my-dearest-ruth-remarkable-devotion-ruth-bader-ginsburgs-husband/, 0.1276595744680851, ['to', 'supreme', 'court', 'justice', 'ruth', 'bader'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [2654, 2688, 2689, 2690, 2691, 2692], False, False, False, True
https://people.howstuffworks.com/10-essential-supreme-court-cases-ruth-bader-ginsburg.htm, 0.10638297872340426, ['supreme', 'court', 'justice', 'ruth', 'bader'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [2092, 2093, 2184, 2185, 2186], False, False, False, True
https://www.usatoday.com/story/news/politics/2018/12/26/ruth-bader-ginsburg-supreme-court-justice-released-hospital/2413300002/, 0.10638297872340426, ['court', 'justice', 'ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [10490, 10492, 10493, 10494, 10495], False, False, False, True
https://www.paperdue.com/topic/criminal-activities-essays/12, 0.10638297872340426, ['court', 'justice', 'ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [6280, 6319, 6320, 6321, 6322], False, False, False, True
http://dldlawyers.com/epl_blog.html, 0.10638297872340426, ['supreme', 'court', 'justice', 'ruth', 'bader'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [22772, 22803, 22852, 22858, 22859], False, False, False, True
https://www.history.com/topics/womens-history/ruth-bader-ginsburg, 0.0851063829787234, ['supreme', 'court', 'justice', 'ruth'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4736, 4737, 4738, 4739], False, True, False, True
https://www.nytimes.com/2019/01/07/us/politics/justice-ginsburg-miss-supreme-court.html, 0.0851063829787234, ['court', 'justice', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [7148, 7164, 7228, 7229], False, False, False, True
https://www.scotusblog.com/2019/04/argument-analysis-court-leaning-toward-requiring-the-government-to-prove-that-a-felon-in-possession-knew-he-was-a-felon/, 0.0851063829787234, ['i', 'think', 'the', 'that'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [3015, 3016, 3097, 3106], False, False, False, True
https://www.ammoland.com/2019/02/second-amendment-supreme-court-and-ruth-bader-ginsburg-february-2019/, 0.0851063829787234, ['would', 'be', 'i', 'think'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4082, 4083, 4103, 4168], False, False, False, True
https://supreme-court.laws.com/ruth-bader-ginsburg, 0.0851063829787234, ['it', 'would', 'be', 'the'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [2504, 2505, 2574, 2586], False, False, False, True
https://www.nbcnews.com/news/us-news/fall-broke-ruth-bader-ginsburg-s-ribs-may-have-saved-n951136, 0.0851063829787234, ['court', 'justice', 'ruth', 'bader'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [5742, 5743, 5744, 5745], False, False, False, True
http://congressionalresearch.com/RL33923/document.php, 0.0851063829787234, ['court', 'justice', 'ruth', 'bader'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [10826, 10894, 10895, 10896], False, False, False, True
http://ufdc.ufl.edu/AA00016616/00056, 0.06382978723404255, ['the', 'is', 'to'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [708, 718, 725], False, False, False, False
http://ufdc.ufl.edu/UF00028315/00822, 0.06382978723404255, ['the', 'is', 'to'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [680, 690, 697], False, False, False, False
http://ufdc.ufl.edu/UF00028315/00184, 0.06382978723404255, ['the', 'is', 'to'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [686, 696, 703], False, False, False, False
http://ufdc.ufl.edu/UF00028321/01044, 0.06382978723404255, ['the', 'is', 'to'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [667, 677, 684], False, False, False, False
https://supremecourthistory.org/history-of-the-court/the-current-court/justice-ruth-bader-ginsburg/, 0.06382978723404255, ['is', 'to', 'supreme'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [41, 43, 92], False, False, False, True
https://www.foxnews.com/category/person/ruth-bader-ginsburg, 0.06382978723404255, ['court', 'justice', 'ruth'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [2538, 2539, 2540], False, False, False, True
https://www.tjhsst.edu/~sgoswami/justices.htm, 0.06382978723404255, ['the', 'that', 'have'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4860, 4868, 4924], False, False, False, True
https://www.buzzfeednews.com/article/chrisgeidner/justice-ruth-bader-ginsburg-is-back-at-the-supreme-court, 0.06382978723404255, ['justice', 'ruth', 'bader'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [8305, 8306, 8307], False, False, False, True
https://www.cbsnews.com/news/ruth-bader-ginsburg-returns-to-work-at-supreme-court-after-surgery-2019-02-15/, 0.06382978723404255, ['to', 'supreme', 'court'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [12004, 12008, 12009], False, False, False, True
https://www.amazon.com/books-used-books-textbooks/b?node=283155, 0.06382978723404255, ['be', 'the', 'we'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [11330, 11345, 11353], False, False, False, False
https://en.wikipedia.org/wiki/Ruth_Bader_Ginsburg, 0.06382978723404255, ['it', 'would', 'be'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [6777, 6778, 6813], False, False, False, True
https://www.washingtonpost.com/politics/courts_law/ruth-bader-ginsburg-makes-first-public-appearance-since-cancer-surgery/2019/02/04/251d59f4-28cf-11e9-b2fc-721718903bfc_story.html, 0.06382978723404255, ['it', 'would', 'be'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [1788, 1789, 1790], False, False, False, True
https://www.researchgate.net/publication/269106585_Ethics_Politics_and_Securities_Law, 0.06382978723404255, ['ruth', 'bader', 'ginsburg'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [59688, 59689, 59690], False, False, False, True
http://www.naked-angel.jp/photobbs.myc/photobbs.cgi?mode=disp&no=3496&page=210, 0.06382978723404255, ['the', 'that', 'we'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [80638, 80647, 80675], False, False, False, True
https://www.redstate.com/, 0.0425531914893617, ['would', 'be'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [2825, 2828], False, False, False, False
https://issuu.com/wescom/docs/bulletin_15-03-2014rtyu, 0.0425531914893617, ['the', 'the'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [1284, 1339], False, False, False, False
https://issuu.com/cardozolaw/docs/cardozolife, 0.0425531914893617, ['the', 'from'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [355, 374], False, False, False, False
https://issuu.com/trronline/docs/28trr_2016, 0.0425531914893617, ['the', 'the'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [1309, 1364], False, False, False, False
https://issuu.com/wescom/docs/bulletin_19-03-2015brcr, 0.0425531914893617, ['the', 'the'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [1284, 1339], False, False, False, False
https://www.politico.com/magazine/story/2019/01/16/ruth-bader-ginsburg-supreme-court-health-224014, 0.0425531914893617, ['supreme', 'court'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [3202, 3203], False, False, False, True
https://www.thefamouspeople.com/profiles/ruth-bader-ginsburg-9292.php, 0.0425531914893617, ['would', 'be'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4122, 4123], False, False, False, True
https://soapboxie.com/government/The-Life-of-Ruth-Bader-Ginsburg-Iconic-Supreme-Court-Justice, 0.0425531914893617, ['i', 'think'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4686, 4687], False, False, False, True
https://www.britannica.com/biography/Ruth-Bader-Ginsburg, 0.0425531914893617, ['would', 'be'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4039, 4040], False, False, False, True
https://www.cnbc.com/2019/01/11/supreme-court-justice-ruth-bader-ginsburg-will-miss-arguments-for-second-week-but-no-further-treatments-planned.html, 0.0425531914893617, ['it', 'would'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4657, 4658], False, False, False, True
https://legalinsurrection.com/2019/01/ruth-bader-ginsburg-watch/, 0.0425531914893617, ['would', 'be'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [5176, 5177], False, False, False, True
https://www.cbsnews.com/news/ruth-bader-ginsburg-lung-cancer-nodules-removed-supreme-court-justice-2018-12-21/, 0.0425531914893617, ['it', 'would'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [3408, 3409], False, False, False, True
https://www.researchgate.net/publication/328626177_Private_Prisons_and_the_New_Marketplace_for_Crime, 0.0425531914893617, ['i', 'think'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [12896, 12897], False, False, False, False
https://en.wikipedia.org/wiki/Sandra_Day_O%27Conner, 0.0425531914893617, ['that', 'we'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [7722, 7723], False, False, False, True
https://www.scribd.com/document/322233183/HOUSE-HEARING-113TH-CONGRESS-VOTING-RIGHTS-ACT-AFTER-THE-SUPREME-COURT-S-DECISION-IN-SHELBY-COUNTY, 0.0425531914893617, ['the', 'that'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [1478, 1496], False, False, False, False
https://www.scribd.com/document/374682199/Henry-Levin-Privatizing-Education-Can-the-Marketplace-Deliver-Choice-Efficiency-Equity-And-Social-Cohesion, 0.0425531914893617, ['the', 'that'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [1465, 1483], False, False, False, False
https://www.inversecondemnation.com/inversecondemnation/land_use_law/page/20/, 0.0425531914893617, ['i', 'think'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [9209, 9211], False, False, False, True
https://www.cnn.com/2019/02/15/politics/ruth-bader-ginsburg-returns-to-supreme-court/index.html, 0.0425531914893617, ['from', 'is'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [32294, 32307], False, False, False, True
https://archive.org/stream/towntopicsprince6243unse/towntopicsprince6243unse_djvu.txt, 0.0425531914893617, ['that', 'we'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [30208, 30209], False, False, False, True
https://www.researchgate.net/publication/274371701_US_Supreme_Court_Justices_and_Public_Mood, 0.0425531914893617, ['i', 'think'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [71141, 71142], False, False, False, True
https://archive.org/stream/barnard854barn/barnard854barn_djvu.txt, 0.0425531914893617, ['i', 'think'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [64381, 64382], False, False, False, True
http://biglizards.net/blog/archives/matrimonial_madness/, 0.0425531914893617, ['i', 'think'], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [4349, 4350], False, False, False, True
https://www.americanthinker.com/blog/2019/01/ruth_bader_ginsburg_watch_nears_the_end_of_its_second_month.html, 0.0, [], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [], False, False, False, True
https://www.oyez.org/justices/ruth_bader_ginsburg, 0.0, [], "f ere was one decision i 0 ld overrule, it would be iti ens united. i think the tion that we have all the emocracy that money n buy strays so far from wht our democracy is supposed to be.' us. supreme court justice ruth bader ginsburg ", [], False, False, False, False
