--------------------------------------------------
Identified names are: ruth bader ginsburg
--------------------------------------------------
--------------------------------------------------
Query string is: ruth bader ginsburg 'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's
--------------------------------------------------


https://www.amightygirl.com/blog?p=18772, 0.775, ['was', 'a', 'law', 'school', 'teacher,', 'and', 'how', 'i', 'regard', 'my', 'role', 'here', 'with', 'my', 'who', 'had', 'the', 'experience', 'of', 'growing', 'up', 'and', 'fully', 'appreciate', 'the', 'arbitrary', 'barriers', 'that', 'have', 'been', 'put'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [4182, 4183, 4184, 4185, 4186, 4187, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4198, 4200, 4201, 4202, 4203, 4204, 4205, 4207, 4209, 4210, 4211, 4212, 4213, 4214, 4215, 4216, 4217], False, False, False, True
https://www.usatoday.com/story/life/entertainthis/2016/03/10/ruth-bader-ginsburg-new-book-my-own-words-most-feminist-quotes/81581010/, 0.75, ['was', 'a', 'law', 'school', 'and', 'how', 'i', 'regard', 'my', 'role', 'here', 'with', 'my', 'who', 'had', 'the', 'experience', 'of', 'growing', 'up', 'and', 'fully', 'appreciate', 'the', 'arbitrary', 'barriers', 'that', 'have', 'been', 'put'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [9372, 9373, 9374, 9375, 9377, 9379, 9380, 9381, 9382, 9383, 9384, 9385, 9386, 9388, 9390, 9391, 9392, 9393, 9394, 9395, 9397, 9399, 9400, 9401, 9402, 9403, 9404, 9405, 9406, 9407], False, False, False, True
http://fortune.com/2015/02/13/the-broadsheet-february-13th/, 0.725, ['was', 'a', 'law', 'school', 'how', 'i', 'regard', 'my', 'role', 'here', 'with', 'my', 'who', 'had', 'the', 'experience', 'of', 'growing', 'up', 'and', 'fully', 'appreciate', 'the', 'arbitrary', 'barriers', 'that', 'have', 'been', 'put'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [3906, 3907, 3908, 3909, 3912, 3913, 3914, 3915, 3916, 3917, 3918, 3919, 3921, 3923, 3924, 3925, 3926, 3927, 3928, 3930, 3932, 3933, 3934, 3935, 3936, 3937, 3938, 3939, 3940], False, False, False, True
https://newslines.org/ruth-bader-ginsburg/, 0.725, ['was', 'a', 'law', 'school', 'how', 'i', 'regard', 'my', 'role', 'here', 'with', 'my', 'who', 'had', 'the', 'experience', 'of', 'growing', 'up', 'and', 'fully', 'appreciate', 'the', 'arbitrary', 'barriers', 'that', 'have', 'been', 'put'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [1442, 1443, 1444, 1445, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1457, 1459, 1460, 1461, 1462, 1463, 1464, 1466, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476], False, False, False, True
https://www.newsmax.com/Newsfront/ginsburg-alarm-womens-rights-scotus/2015/02/12/id/624473/, 0.725, ['was', 'a', 'law', 'school', 'how', 'i', 'regard', 'my', 'role', 'here', 'with', 'my', 'who', 'had', 'the', 'experience', 'of', 'growing', 'up', 'and', 'fully', 'appreciate', 'the', 'arbitrary', 'barriers', 'that', 'have', 'been', 'put'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [2985, 2986, 2987, 2988, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3023, 3025, 3026, 3027, 3028, 3029, 3030, 3032, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042], False, False, False, True
https://www.bustle.com/articles/90391-these-8-ruth-bader-ginsburg-quotes-about-gender-discrimination-make-it-clear-the-movie-about-her, 0.25, ['was', 'a', 'law', 'school', 'and', 'how', 'i', 'regard', 'my', 'role'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [1601, 1602, 1603, 1604, 1606, 1608, 1609, 1610, 1611, 1612], False, False, False, True
https://www.cosmopolitan.com/politics/news/a61317/ruth-bader-ginsburg-is-goals-af/, 0.25, ['was', 'a', 'law', 'school', 'how', 'i', 'regard', 'my', 'role', 'here'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [3027, 3028, 3029, 3030, 3036, 3037, 3038, 3039, 3040, 3041], False, False, False, True
https://www.bloomberg.com/news/features/2015-02-12/ruth-bader-ginsburg-isn-t-giving-up-her-fight-for-women-s-rights, 0.125, ['a', 'and', 'of', 'and', 'the'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [457, 481, 500, 502, 529], False, False, False, False
https://www.pinterest.com/pin/286260120048264721/, 0.1, ['who', 'the', 'of', 'and'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [3127, 3129, 3131, 3136], False, False, False, False
https://www.pinterest.com/pin/570760952745878862/, 0.075, ['who', 'the', 'of'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [4730, 4766, 4768], False, False, False, False
https://rareddit.com/r/TwoXChromosomes/comments/9q02s2/abortions_by_mail_are_available_now_in_the_us/, 0.075, ['the', 'that', 'have'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [54186, 54191, 54238], False, False, False, True
https://archive.org/stream/Sep25Oct22015/Sep25-Oct22015_djvu.txt, 0.075, ['who', 'had', 'the'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [32956, 32958, 32959], False, False, False, True
https://familycourtmatters.org/category/til-death-do-us-part-literally/, 0.075, ['of', 'growing', 'up'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [53022, 53023, 53024], False, False, False, True
https://www.achievement.org/achiever/ruth-bader-ginsburg/, 0.05, ['a', 'law'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [8362, 8363], False, False, False, True
https://academic.oup.com/icon/article/15/3/602/4582632, 0.05, ['law', 'school'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [5227, 5228], False, False, False, True
https://iacc.hhs.gov/meetings/public-comments/requests-for-information/2016/responses/question6.shtml, 0.05, ['my', 'role'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [74530, 74531], False, False, False, True
http://nasygnale.info/galeria/Wypadek_13-10-2014_w_Wejherowie,126,1838.html, 0.05, ['a', 'law'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [3266, 3269], False, False, False, True
https://familycourtmatters.org/category/lethality-indicators-in-news/, 0.05, ['a', 'law'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [26559, 26561], False, False, False, True
http://sol-war.ru/health.html, 0.05, ['the', 'arbitrary'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [85238, 85248], False, False, False, True
http://www.fixcas.com/news/2011/b2011f.htm, 0.05, ['a', 'law'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [63089, 63090], False, False, False, True
http://www.akdart.com/lib9.html, 0.05, ['have', 'been'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [150155, 150156], False, False, False, True
https://www.metafilter.com/165353/State-of-a-divided-union/rss, 0.05, ['and', "that's"], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [70339, 70340], False, True, False, True
https://epdf.tips/a-to-z-of-american-women-leaders-and-activists-a-to-z-of-women.html, 0.05, ['male', 'colleagues'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [59946, 59947], False, False, False, True
http://www.27east.com/news/article.cfm/Westhampton-Beach-Surrounding-Areas/58802/Woman-Hoping-Local-Cops-Can-Be-Eduacated-About-Breastfeeding, 0.05, ['the', 'experience'], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [41123, 41124], False, False, False, True
https://issuu.com/sfnewmexican/docs/dyx0oe, 0.0, [], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [], False, False, False, False
https://wiki2.org/en/Ruth_Bader_Ginsburg, 0.0, [], "'l was a law school teacher, and that's how i regard my role here with my male colleagues who haven't had the experience of growing up female, and don't fully appreciate the arbitrary barriers that have been put in women's ", [], False, False, False, False
