--------------------------------------------------
Identified names are: hillary clinton witw
--------------------------------------------------
--------------------------------------------------
Query string is: hillary clinton witw 'take criticism seriously but not personally
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton witw hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton witw you're not your critics
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton witw you're not your work
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton witw you're you
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
https://www.azquotes.com/quote/868829, 0.25, ['criticism', 'seriously', 'not', 'personally.', 'hillary', 'clinton', 'at'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [25, 26, 28, 29, 31, 32, 34], False, False, False, True
https://www.pinterest.com/pin/1618549843206049/, 0.21428571428571427, ['criticism', 'but', 'not', 'personally.', 'hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3307, 3309, 3310, 3311, 3345, 3346], False, False, False, True
https://historyweblog.com/2016/08/hillary-clinton-taking-criticism/, 0.21428571428571427, ['criticism', 'but', 'not', 'personally.', 'hillary', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [518, 520, 521, 522, 546, 560], False, False, False, True
https://www.azquotes.com/author/2997-Hillary_Clinton/tag/criticism, 0.21428571428571427, ['criticism', 'seriously', 'but', 'not', 'hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3535, 3536, 3537, 3538, 3590, 3591], False, False, False, True
http://www.dailykos.com/story/2016/5/10/1525008/-Hillary-Hangout-05-10-16-Take-criticism-seriously-but-not-personally, 0.21428571428571427, ["'take", 'criticism', 'but', 'not', 'hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [180, 181, 183, 184, 196, 197], False, False, False, True
https://www.youtube.com/watch?v=MAXHfHdFoqQ, 0.21428571428571427, ['criticism', 'seriously', 'but', 'not', 'hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [545, 546, 547, 548, 561, 563], False, False, False, True
https://www.tlnt.com/shrm-chicago-insights-take-criticism-seriously-but-not-personally/, 0.17857142857142858, ['criticism', 'seriously', 'but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [233, 234, 235, 236, 237], False, False, False, True
https://quotefancy.com/quote/828988/Hillary-Clinton-Take-criticism-seriously-but-not-personally-If-there-is-truth-or-merit-in, 0.17857142857142858, ['criticism', 'but', 'not', 'personally.', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1385, 1387, 1388, 1389, 1413], False, False, False, True
https://womensagenda.com.au/leadership/advice/take-criticism-on-board-but-don-t-take-it-personally-hillary-clinton-s-advice-to-professional-women/, 0.17857142857142858, ['criticism', 'seriously', 'but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2509, 2510, 2511, 2512, 2513], False, False, False, True
https://www.goodreads.com/work/quotes/24806264-hard-choices, 0.17857142857142858, ['criticism', 'seriously', 'but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [5863, 5864, 5865, 5866, 5867], False, False, False, True
https://www.success.com/6-questions-to-help-you-handle-criticism/, 0.14285714285714285, ['criticism', 'seriously', 'but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1945, 1946, 1947, 1948], False, False, False, True
https://www.linkedin.com/pulse/20140616153520-198970493-take-criticism-seriously-not-personally, 0.14285714285714285, ['criticism', 'seriously', 'but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [375, 376, 377, 378], False, False, False, True
https://www.cemiddleton.com/post/117164582731/take-criticism-seriously-but-not-personally, 0.14285714285714285, ['criticism', 'but', 'not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [884, 886, 887, 889], False, False, False, True
https://www.breitbart.com/politics/2019/03/13/lisa-page-obama-doj-ordered-fbi-not-to-prosecute-hillary-clinton/, 0.14285714285714285, ['not', 'hillary', 'clinton', 'by'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1082, 1086, 1087, 1116], False, False, False, True
https://www.lifezette.com/2019/05/man-interrupts-hillary-clinton-speaking-event-youre-going-to-jail-lady/, 0.14285714285714285, ['but', 'not', 'hillary', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1561, 1562, 1564, 1597], False, False, False, True
http://theeverygirl.com/how-to-take-critical-feedback-at-work-like-a-boss/, 0.14285714285714285, ['criticism', 'seriously', 'but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1273, 1274, 1286, 1323], False, False, False, True
https://www.nationalmemo.com/hillary-clintons-advice-young-women-dont-get-dragged-critics/, 0.14285714285714285, ['criticism', 'but', 'not', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [5120, 5122, 5123, 5139], False, False, False, True
https://www.goodreads.com/work/quotes/480368-living-history, 0.14285714285714285, ['criticism', 'but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [10968, 10970, 10971, 10972], False, False, False, True
https://www.politico.com/amp/story/2019/05/01/hillary-clinton-china-tax-returns-1296868, 0.10714285714285714, ['clinton', 'by', 'at'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1667, 1681, 1711], False, False, False, True
https://www.dailywire.com/news/44587/obama-doj-told-fbi-not-charge-hillary-lisa-page-ryan-saavedra, 0.10714285714285714, ['not', 'clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2656, 2658, 2706], False, False, False, True
https://www.snopes.com/fact-check/hillary-clinton-victims-of-war/, 0.10714285714285714, ['not', 'your', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2819, 2823, 2834], False, True, False, True
https://www.brainyquote.com/authors/hillary_clinton, 0.10714285714285714, ['hillary', 'clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1122, 1123, 1126], False, False, False, True
https://www.newsweek.com/chelsea-clinton-hits-out-fake-photo-hillary-clinton-blackface-looks-nothing-1321567, 0.10714285714285714, ['hillary', 'clinton', 'by'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [5440, 5441, 5450], False, False, False, True
https://careergasm.com/criticism/, 0.10714285714285714, ['not', 'hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2151, 2202, 2203], False, False, False, True
https://thoughtcatalog.com/nico-lang/2013/08/33-badass-hillary-clinton-quotes-that-prove-why-she-should-be-our-first-female-president/, 0.10714285714285714, ['but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [5348, 5349, 5350], False, False, False, True
https://www.foxnews.com/politics/bill-kristol-slammed-giuliani-senate-race-stronger-clinton-cancer-diagnosis, 0.10714285714285714, ['by', 'not', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2642, 2688, 2689], False, False, False, True
https://www.pinterest.com/pin/16395986118478310/, 0.10714285714285714, ['but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2989, 2990, 2991], False, False, False, True
https://www.politico.com/story/2019/05/01/hillary-clinton-china-tax-returns-1296868, 0.10714285714285714, ['not', 'clinton', 'by'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1679, 1693, 1707], False, False, False, True
https://www.psychologytoday.com/us/blog/the-situation-lab/201610/the-personality-hillary-clinton, 0.10714285714285714, ['not', 'hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [6140, 6148, 6149], False, False, False, True
https://spectator.us/miss-hillary-clinton-kamala-harris/, 0.10714285714285714, ['your', 'not', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [4233, 4246, 4256], False, False, False, True
https://www.youtube.com/watch?v=NJxmpTMGhU0, 0.10714285714285714, ['hillary', 'clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [473, 474, 493], False, False, False, True
https://www.tmz.com/2019/02/28/fake-hillary-clinton-dollar-bill-prison-signed-donald-trump-auction-block/, 0.10714285714285714, ['hillary', 'clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3766, 3767, 3788], False, False, False, True
https://www.youtube.com/watch?v=IeCWs4xf7EU, 0.10714285714285714, ['hillary', 'clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [4123, 4124, 4133], False, False, False, True
https://www.reddit.com/r/hillaryclinton/comments/4lt9cj/i_adopted_my_own_mantra_take_criticism_seriously/, 0.10714285714285714, ['but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3262, 3263, 3264], False, False, False, True
https://www.broadwayworld.com/reviews/Hillary-and-Clinton, 0.10714285714285714, ['hillary', 'clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [4289, 4291, 4317], False, False, False, True
https://www.marieclaire.com/career-advice/tips/a11373/best-hillary-clinton-quotes/, 0.10714285714285714, ['but', 'not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2313, 2314, 2315], False, False, False, True
https://parade.com/879897/janicekaplan/laurie-metcalf-on-playing-hillary-clinton-on-broadway-this-hillary-may-not-be-the-one-you-think-you-know/, 0.10714285714285714, ['not', 'hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [9346, 9365, 9366], False, False, False, True
https://www.theguardian.com/world/2014/mar/14/hillary-clinton-nasty-palace-politics-princess-diana-funeral, 0.10714285714285714, ['criticism', 'but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [18048, 18050, 18051], False, False, False, True
https://www.theguardian.com/world/2014/feb/13/hillary-clinton-melinda-gates-women-criticism, 0.10714285714285714, ['criticism', 'seriously', 'but'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [15788, 15789, 15823], False, False, False, True
https://en.wikipedia.org/wiki/Hillary_Clinton_2016_presidential_campaign, 0.10714285714285714, ['clinton', 'this', 'quote'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [9353, 9356, 9401], False, True, False, True
https://www.washingtonpost.com/opinions/seems-like-everyones-colluding-with-russia-now/2017/10/30/25d3e122-bdb6-11e7-8444-a0d4f04b89eb_story.html, 0.10714285714285714, ['hillary', 'clinton', 'quote'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1666, 1685, 1701], False, False, False, True
https://www.hillaryclinton.com/issues/national-security/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [640, 641], False, False, False, True
https://www.themuse.com/advice/the-secret-to-taking-criticism-seriouslynot-personally, 0.07142857142857142, ['not', 'personally.'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1078, 1079], False, False, False, True
https://www.mic.com/articles/116152/12-quotes-from-hillary-clinton-show-her-remarkable-defiance, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2173, 2174], False, False, False, True
https://www.snopes.com/fact-check/hillary-or-karl/, 0.07142857142857142, ['by', 'at'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2728, 2732], False, True, False, True
https://www.realclearpolitics.com/video/2015/08/18/black_lives_matter_confronts_hillary_clinton_in_overflow_room_you_dont_change_hearts.html, 0.07142857142857142, ['not', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3038, 3055], False, False, False, True
https://www.thoughtco.com/hillary-clinton-quotes-3525393, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2810, 2812], False, False, False, True
http://politicalticker.blogs.cnn.com/2014/02/13/clinton-on-taking-criticism-dont-get-dragged-down/, 0.07142857142857142, ['criticism', 'but'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [147, 149], False, False, False, True
https://www.washingtontimes.com/news/2019/may/2/hillary-clinton-china-if-youre-listening-why-dont-/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3655, 3656], False, False, False, True
https://thedailybanter.com/2016/03/07/a-hillary-clintonbernie-sanders-ticket-with-president-obamas-support-would-be-near-unstoppable/, 0.07142857142857142, ['particularly', 'hits'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3035, 3039], False, False, False, True
https://www.realclearpolitics.com/video/2015/10/22/rep_jim_jordan_vs_hillary_clinton_why_did_you_tell_egyptians_benghazi_was_a_terrorist_attack_but_not_the_american_people.html#!, 0.07142857142857142, ['but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3953, 3954], False, False, False, True
https://www.hillaryclinton.com/issues/, 0.07142857142857142, ['this', 'by'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [666, 715], False, False, False, True
https://www.foxnews.com/entertainment/maher-blasts-hillary-clinton-for-stealing-his-china-if-youre-listening-act, 0.07142857142857142, ['your', "you're"], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2518, 2538], False, False, False, True
https://www.realclearpolitics.com/video/2019/04/14/hillary_clinton_were_in_a_twilight_zone_on_mueller_report.html, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [525, 526], False, False, False, True
https://www.breitbart.com/clips/2019/04/23/hillary-clinton-it-could-not-be-clearer-trump-would-be-indicted-for-obstruction-if-he-wasnt-potus/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [877, 878], False, False, False, True
https://nystagereview.com/2019/04/18/hillary-and-clinton-couples-therapy-for-the-audience/, 0.07142857142857142, ['not', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2864, 2874], False, False, False, True
https://www.portsmouthhigh.co.uk/welcome/heads-blog/hillary-clinton-said-take-criticism-seriously-not-personally, 0.07142857142857142, ['criticism', 'seriously'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [299, 300], False, False, False, True
https://www.lifezette.com/2019/05/bill-hillary-clinton-speaking-tickets-drop-to-20-person/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1792, 1793], False, False, False, True
https://www.louderwithcrowder.com/dear-hillary-clinton-you-lost-because-america-hates-you/, 0.07142857142857142, ['your', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3441, 3444], False, False, False, True
https://crooksandliars.com/2019/05/clinton-interview-draft, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [295, 296], False, False, False, True
https://www.newsmax.com/thewire/tour-deplorable-lock-her-up-speech/2019/05/06/id/914734/, 0.07142857142857142, ['clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3088, 3120], False, False, False, True
https://www.breitbart.com/clips/2019/05/02/hillary-clinton-china-if-youre-listening-why-dont-you-get-trumps-tax-returns/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [836, 837], False, False, False, True
https://www.outsidethebeltway.com/hillary-clinton-to-libyan-war-critics-whose-side-are-you-on/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2313, 2314], False, False, False, True
https://www.politico.com/story/2014/06/hillary-clinton-book-107570, 0.07142857142857142, ['not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1940, 1944], False, False, False, True
https://www.latimes.com/politics/la-xpm-2014-feb-14-la-pn-hillary-clinton-advice-to-women-20140214-story.html, 0.07142857142857142, ['not', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2563, 2573], False, False, False, True
https://www.chicagotribune.com/entertainment/theater/ct-ae-laurie-metcalf-jones-0519-story.html, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3150, 3151], False, False, False, True
https://www.detroitnews.com/story/news/local/detroit-city/2019/04/12/bill-hillary-clinton-fox-theater-talk/3431924002/, 0.07142857142857142, ['but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [10146, 10147], False, False, False, True
http://www.elderstatement.com/2019/05/bill-maher-blasts-hillary-clinton-for.html, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [269, 270], False, False, False, True
https://thehill.com/homenews/administration/441758-clinton-makes-hypothetical-joke-china-if-youre-listening-why-dont-you, 0.07142857142857142, ['not', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [543, 584], False, False, False, True
https://www.youtube.com/watch?v=Z0xlQkC4dE0, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1987, 1988], False, False, False, True
https://www.elle.com/culture/career-politics/news/a40653/hillary-clinton-inspiring-quotes/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [4151, 4152], False, False, False, True
https://thehill.com/homenews/media/355533-tomi-lahren-slams-hillary-clinton-on-weinstein-criticism-youre-still-married, 0.07142857142857142, ['this', 'by'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3580, 3627], False, False, False, True
https://thepoliticalinsider.com/hillary-clinton-says-male-democrat-candidates-are-not-likable/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [4571, 4593], False, False, False, True
https://fellowshipoftheminds.com/hillary-clinton-threatens-her-twitter-critics-were-coming-back-at-you, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3110, 3111], False, False, False, True
https://www.youtube.com/watch?v=IEz8zbUN030, 0.07142857142857142, ['at', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [4270, 4288], False, False, False, True
https://www.youtube.com/watch?v=o_Ws02SogMk, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3973, 3974], False, False, False, True
https://www.lookhuman.com/collection/1030-hillary-2016, 0.07142857142857142, ['this', 'quote'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2201, 2209], True, True, False, True
https://www.rushlimbaugh.com/daily/2019/04/18/no-barr-did-not-just-exonerate-hillary/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [6032, 6033], False, False, False, True
https://www.ndtv.com/world-news/full-transcript-of-hillary-clintons-interview-with-ndtv-1753521, 0.07142857142857142, ['your', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [8027, 8044], False, False, False, True
https://www.newsweek.com/trevor-noah-hillary-clinton-lewinsky-1171741, 0.07142857142857142, ['at', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [7844, 7852], False, False, False, True
https://www.usatoday.com/story/news/politics/2017/11/05/brazile-critics-her-book-critical-hillary-clinton-campaign-can-go-hell/833715001/, 0.07142857142857142, ['not', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [13009, 13032], False, False, False, True
http://time.com/3772504/how-hillary-clinton-will-handle-populist-critics/, 0.07142857142857142, ['by', 'at'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [6268, 6316], False, False, False, True
https://abcnews.go.com/WNT/video/hillary-clinton-takes-critics-abc-news-exclusive-23631522, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [185, 186], False, False, False, True
http://time.com/4716858/hillary-clinton-businesswomen-california-transcript/, 0.07142857142857142, ['at', 'particularly'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [4127, 4138], False, False, False, True
https://www.azquotes.com/author/2997-Hillary_Clinton, 0.07142857142857142, ['this', 'quote'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [7468, 7471], False, False, False, True
https://www.usatoday.com/story/news/politics/2019/05/01/hillary-clinton-democrats-china-donald-trumps-tax-returns/3647913002/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [8443, 8444], False, False, False, True
https://www.businessinsider.com/china-listening-hillary-clinton-jabs-trump-us-cybersecurity-issues-2019-5, 0.07142857142857142, ['clinton', 'this'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1193, 1196], False, False, False, True
https://www.nytimes.com/2016/07/28/us/politics/donald-trump-russia-clinton-emails.html, 0.07142857142857142, ['by', 'at'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [9185, 9241], False, False, False, True
https://www.reddit.com/r/hillaryclinton/comments/b7ix5m/hillary_clinton_spokesman_slams_pete_buttigieg/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [9827, 9831], False, False, False, True
https://freedomoutpost.com/are-bill-hillary-clinton-involved-with-child-trafficking/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [8005, 8007], False, False, False, True
https://news.yahoo.com/hillary-clinton-gives-dramatic-reading-of-the-mueller-report-162351812.html, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [7356, 7357], False, True, False, True
https://www.desertsun.com/story/news/politics/elections/2016/05/24/hillary-clintons-campaign-swings-riverside-rally-soon/84875304/, 0.07142857142857142, ['by', 'at'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [10544, 10558], False, False, False, True
https://answers.yahoo.com/question/index?qid=20080311122649AA6UR7G, 0.07142857142857142, ['at', "you're"], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3444, 3447], False, False, False, True
https://www.cosmopolitan.com/politics/a3700858/hillary-clinton-reservations-criticism/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [6199, 6200], False, False, False, True
https://newspunch.com/nypd-hillary-clinton-child-sex-scandal/, 0.07142857142857142, ['your', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [7866, 7877], False, False, False, True
https://www.fastcompany.com/4034186/hillary-clinton-says-women-should-take-criticism-seriously-but-not-personally, 0.07142857142857142, ['criticism', 'seriously'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [5709, 5710], False, False, False, True
https://reason.com/2011/06/24/hillary-clinton-to-libya-war-c, 0.07142857142857142, ['at', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [11270, 11286], False, False, False, True
https://www.nytimes.com/2017/05/09/us/politics/james-comey-fired-fbi.html, 0.07142857142857142, ['not', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [10528, 10559], False, False, False, True
https://wattsupwiththat.com/2017/09/11/hillary-clinton-threatening-coal-jobs-was-a-mistake/, 0.07142857142857142, ['but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [3983, 4014], False, False, False, True
https://www.huffingtonpost.com/2014/03/04/hillary-clinton-quotes-lisa-rogak_n_4770130.html, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [7735, 7736], False, False, False, True
https://www.thedailybeast.com/how-brian-fallon-hillary-clintons-press-secretary-self-radicalized-and-became-a-resistance-leader, 0.07142857142857142, ['not', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [20840, 20848], False, False, False, True
https://rationalwiki.org/wiki/Hillary_Clinton, 0.07142857142857142, ['not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [10232, 10274], False, True, False, True
https://www.theguardian.com/books/2017/sep/18/what-happened-hillary-rodham-clinton-review, 0.07142857142857142, ['but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [15433, 15449], False, False, False, True
https://www.dailymail.co.uk/news/article-6985251/China-youre-listening-dont-Trumps-tax-returns-Hillary-Clinton-trolls-Trump.html, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [5695, 5696], False, False, False, True
http://www.returnofkings.com/93777/hillary-and-bill-clinton-are-criminal-masterminds-wielding-incredible-power, 0.07142857142857142, ['not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [19339, 19348], False, False, False, True
https://www.cnn.com/2018/10/09/politics/hillary-clinton-civility-congress-cnntv/index.html, 0.07142857142857142, ['but', 'not'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [24428, 24439], False, False, False, True
https://www.goodreads.com/book/show/56073.Living_History, 0.07142857142857142, ['not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [7280, 7285], False, False, False, True
https://www.vanityfair.com/style/2019/05/hillary-and-clinton-barack-obama-real-life-tailor-interview, 0.07142857142857142, ['not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [37929, 37934], False, False, False, True
https://www.hillaryis44.org/2008/08/21/stephanies-superdelegate-hillary-clinton-smile/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [18898, 18903], False, True, False, True
https://www.washingtonpost.com/entertainment/theater_dance/making-a-play-about-real-people-is-always-challenging--now-imagine-if-its-bill-and-hillary-clinton/2019/05/09/f87297de-6f4b-11e9-9f06-5fc2ee80027a_story.html, 0.07142857142857142, ['not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [2736, 2745], False, False, False, True
https://en.wikipedia.org/wiki/Hillary_Clinton, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [31984, 31995], False, True, False, True
https://en.wikipedia.org/wiki/Hillary_Rodham_Clinton, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [32000, 32011], False, True, False, True
https://www.washingtonpost.com/politics/hillary-clinton-china-if-youre-listening-why-dont-you-get-trumps-tax-returns/2019/05/02/6d2310f6-6cca-11e9-8f44-e8d8bb1df986_story.html, 0.07142857142857142, ['not', 'hillary'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [1758, 1760], False, False, False, True
http://time.com/collection/firsts/4921038/hillary-clinton-firsts/, 0.07142857142857142, ['not', 'your'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [64503, 64523], False, False, False, True
https://www.facebook.com/pg/hillaryclinton/posts/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [9701, 9702], False, False, True, True
https://www.pinterest.com/hillaryclinton/, 0.07142857142857142, ['hillary', 'clinton'], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [56895, 56909], False, False, False, True
https://www.hillaryclinton.com/, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, False, True
https://twitter.com/HillaryClinton/status/796394920051441664, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, True, True
https://twitter.com/HillaryClinton/status/1103067043048419329, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, True, True
https://www.politico.com/story/2019/02/25/bernie-sanders-hillary-clinton-private-jet-flights-1182793, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, False, True
https://www.usmagazine.com/celebrity-news/news/hillary-clinton-responds-to-critics-who-say-she-should-smile-more-w438742/, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, False, True
https://twitter.com/HillaryClinton/status/1128668280913387521, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, True, True
https://twitter.com/hillaryclinton, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, True, True
https://www.youtube.com/watch?v=MOLVnqQUoqg, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, False, True
https://www.nytimes.com/2015/12/24/us/politics/hillary-clinton-is-not-my-abuela-critics-say.html, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, False, True
https://www.usatoday.com/story/news/politics/onpolitics/2018/10/09/hillary-clinton-cnn-interview/1578636002/, 0.0, [], "'take criticism seriously but not personally. hillary clinton this quote by hillaryclinton at womenlntheworld particularly hits home. you're not your critics. you're not your work. you're you. witw ", [], False, False, False, True
