--------------------------------------------------
Identified names are: pete rouse
--------------------------------------------------
--------------------------------------------------
Query string is: pete rouse if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress
--------------------------------------------------


--------------------------------------------------
Query string is: pete rouse o barack obama bama quoteshdwallpapers.com
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 503: Service Unavailable
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 406: Not Acceptable
https://www.wnd.com/2012/08/the-return-of-obamas-body-man/, 0.2, ['if', 'you', 'the', 'and', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [3778, 3779, 3791, 3794, 3804], False, False, False, True
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Barack_Obama/articles, 0.12, ['the', 'and', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [2447, 2464, 2480], False, False, False, True
https://www.politico.com/story/2008/11/emanuel-accepts-white-house-job-015371, 0.12, ['the', 'and', 'to'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [1932, 1939, 1960], False, False, False, True
https://www.pbs.org/wgbh/pages/frontline/dreamsofobama/etc/script.html, 0.12, ['the', 'and', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [7538, 7555, 7572], False, False, False, True
https://helynshow.wordpress.com/, 0.12, ['you', 'to', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [7491, 7531, 7535], False, False, False, True
https://www.politico.com/tipsheets/huddle/2011/12/tax-fight-two-steps-back-inouyes-dilemma-boehner-to-playbook-breakfast-senates-secret-santa-clause-blunt-is-back-pelosi-vs-richardson-rubio-dnc-in-war-or-words-issa-hits-occupy-stimulus-004577, 0.12, ['the', 'and', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [4152, 4161, 4196], False, False, False, True
https://www.pinterest.com/pedropablocabre/inspiring-law-quotes/, 0.12, ['the', 'right', 'path'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [15114, 15115, 15116], False, False, False, False
https://www.pbs.org/wgbh/pages/frontline//choice2008/obama/agenda.html, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [714, 715], False, False, False, True
http://www.answers.com/Q/Why_was_Barack_Obama_named_Barack_Hussein_Obama, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [1626, 1627], False, False, False, False
https://www.answers.com/Q/Is_Barack_Hussein_Obama_an_egomaniac, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [1686, 1688], False, False, False, False
https://presidentbarackhobama.blogspot.com/2008/11/mona-sutphen.html, 0.08, ['the', 'and'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [1103, 1117], False, False, False, True
https://populartopicosos.blogspot.com/2011/01/obama-chooses-william-daley-for-chief.html, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [2784, 2785], False, False, False, True
https://www.politifact.com/truth-o-meter/article/2017/aug/04/donald-trumps-white-house-turnover-context/, 0.08, ['and', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [2959, 2996], False, True, False, True
https://alleyesonabama.blogspot.com/2011/01/obama-is-considering-naming-jp-morgan.html, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [4389, 4390], False, False, False, True
https://www.politico.com/news/stories/0311/52071_Page2.html, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [2774, 2782], False, False, False, True
https://edition.cnn.com/TRANSCRIPTS/1010/01/sitroom.01.html, 0.08, ['and', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [6509, 6510], False, False, False, True
https://www.whitehousedossier.com/tag/rahm/, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [2483, 2484], False, False, False, True
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Barack_Obama, 0.08, ['if', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [912, 913], False, False, False, True
https://www.americanrhetoric.com/speeches/barackobama/barackobamafinal2013presser.htm, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [8797, 8799], False, False, False, True
https://barackoteering.blogspot.com/, 0.08, ['to', 'make'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [8851, 8864], False, False, False, True
https://www.politico.com/tipsheets/playbook/2013/01/obama-to-new-republic-sensible-package-including-medicare-reform-may-help-break-gop-fever-shoots-skeet-at-camp-david-football-may-become-a-little-less-exciting-to-protect-players-009907, 0.08, ['you', 'the'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [3776, 3790], False, False, False, True
https://www.nytimes.com/2010/10/17/magazine/17obama-t.html, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [4412, 4413], False, False, False, True
https://umoc193.wordpress.com/category/military/, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [12873, 12874], False, True, False, True
https://www.fanfiction.net/s/12983228/5/How-To-Take-Care-Of-Your-Spider-Child-And-Other-Questionable-Ideas, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [8695, 8696], False, False, False, True
https://www.politico.eu/article/obamas-obama-unfulfilled-campaign-promises-white-house/, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [6329, 6330], False, False, False, True
https://shotoshinkai.blogspot.com/2013/09/shotoshinkai-history.html, 0.08, ['if', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [7223, 7224], False, False, False, True
https://www.huffpost.com/news/topic/obama-cabinet, 0.08, ['to', 'eventually'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [13163, 13166], False, False, False, True
http://www.warr.org/odds.html, 0.08, ['if', 'you'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [5393, 5394], False, False, False, True
https://www.pinterest.com/tpmmedia/fist-bumper-in-chief/, 0.08, ['the', 'path'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [5642, 5652], False, False, False, True
https://en.wikipedia.org/wiki/X_(Ed_Sheeran_album), 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [1997, 1998], False, False, False, True
https://www.pinterest.com/piotrlech/law/, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [7587, 7590], False, False, False, False
https://www.cbsnews.com/news/obama-unveils-presidential-transition-team/, 0.08, ['right', 'and'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [1546, 1591], False, False, False, True
https://en.wikipedia.org/wiki/Rom_Emanuel, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [12017, 12018], False, False, False, True
https://www.barnesandnoble.com/w/leading-from-behind-richard-miniter/1111307414, 0.08, ['to', 'eventually'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [15292, 15300], False, False, False, True
https://seitokarate.blogspot.com/2008/05/welcome-to-original-karate-blog.html, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [6889, 6890], False, False, False, True
https://www.hillaryis44.org/page/102/, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [16683, 16684], False, False, False, True
https://archive.org/details/FOXNEWS_20101001_150000_Happening_Now, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [23118, 23119], False, False, False, True
https://theobamadiary.com/tag/koch-brothers/, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [22726, 22727], False, True, False, True
https://in.pinterest.com/kevinfinke/words-are-powerful/, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [28950, 28951], False, False, False, False
https://fr.wikipedia.org/wiki/Administration_Obama, 0.08, ['barack', 'obama'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [34906, 34907], False, False, False, True
https://theobamadiary.com/tag/energy/page/2/, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [31119, 31120], False, False, False, True
https://en.wikipedia.org/wiki/Presidency_of_Barack_Obama, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [19802, 19803], False, True, False, True
https://www.yahoo.com/entertainment/might-serve-second-obama-administration-010227537--politics.html, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [8821, 8822], False, False, False, True
https://en.wikipedia.org/wiki/Obama_regime, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [19842, 19843], False, True, False, True
https://www.hillaryis44.org/2010/10/07/treacheries-untold-why-hillary-clinton-must-not-run-for-president-ever-again/, 0.08, ['to', 'keep'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [44590, 44591], False, False, False, True
https://infogalactic.com/info/Presidency_of_Barack_Obama, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [18257, 18258], False, False, False, True
https://www.washingtonpost.com/politics/, 0.08, ['the', 'right'], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [1555, 1558], False, False, False, False
http://apps.frontline.org/divided-states-of-america-the-frontline-interviews/transcript/pete-rouse.html, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, True
https://issuu.com/stmartinspress/docs/leadingfrombehind-excerpt, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, False
https://issuu.com/peninsuladailynews/docs/s964jn20120110c, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, False
https://wiki2.org/en/United_States_Senate_career_of_Barack_Obama, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, False
https://dailycaller.com/2011/09/16/claim-treasury-secretary-ignored-obama-directive/, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, True
https://www.nationalreview.com/2013/12/wrong-kind-white-house-shake-john-fund/, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, True, False, True
http://www.finance1online.com/obama-poster/, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, True
https://pl.wikipedia.org/wiki/Barack_Obama, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, True
https://www.pinterest.com/JoyfulMemories/high-crimes-misdemeanors/, 0.0, [], "if you 're walking down the right path and you 're willing to keep walking, eventually you 'ii make progress. o barack obama bama quoteshdwallpapers.com ", [], False, False, False, True
