--------------------------------------------------
Identified names are: barack obama
--------------------------------------------------
--------------------------------------------------
Query string is: barack obama we need affordable, highquality childcare mare than ever
--------------------------------------------------


--------------------------------------------------
Query string is: barack obama it's not a nicetohave t's a musthave
--------------------------------------------------


--------------------------------------------------
Query string is: barack obama 111lojqen' m "florida president obama
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
https://mic.com/articles/108830/if-you-are-a-woman-these-are-the-6-lines-from-obama-s-sotu-speech-you-need-to-read, 0.4, ['we', 'need', 'affordable,', 'childcare', 'than', 'ever.', 'not', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1580, 1581, 1582, 1584, 1586, 1587, 1589, 1607], False, False, False, True
https://www.theguardian.com/money/2015/jan/23/obama-better-childcare-raise-childgivers-pay, 0.4, ['we', 'need', 'affordable,', 'childcare', 'than', 'not', 'a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [15518, 15519, 15520, 15522, 15524, 15529, 15543, 15547], False, False, False, True
https://qz.com/330241/obama-is-right-childcare-in-america-is-insanely-expensive/, 0.35, ['we', 'need', 'affordable,', 'childcare', 'than', 'ever.', 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2124, 2125, 2126, 2128, 2130, 2131, 2133], False, False, False, True
https://www.democracynow.org/2015/1/21/ralph_nader_on_what_was_missing, 0.35, ['we', 'need', 'affordable,', 'than', 'ever.', 'not', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2446, 2447, 2448, 2453, 2454, 2456, 2475], False, False, False, True
https://www.louderwithcrowder.com/nine-big-lies-obama-told-state-union-speech-2/, 0.3, ['need', 'affordable,', 'childcare', 'than', 'ever.', 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2138, 2139, 2141, 2143, 2144, 2146], False, False, False, True
https://www.onenewspage.com/video/20150121/2470834/Affordable-Childcare-Must-Have-Obama.htm, 0.3, ['we', 'need', 'affordable,', 'childcare', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [768, 769, 770, 772, 774, 775], False, False, False, True
https://obamawhitehouse.archives.gov/the-press-office/2015/01/21/fact-sheet-helping-all-working-families-young-children-afford-child-care, 0.3, ['we', 'need', 'affordable,', 'childcare', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2784, 2785, 2786, 2788, 2790, 2791], False, False, False, True
https://www.youtube.com/watch?v=3KoU8TzlbSk, 0.3, ['we', 'need', 'affordable,', 'childcare', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3123, 3124, 3125, 3127, 3129, 3130], False, False, False, True
https://www.breitbart.com/politics/2015/01/20/obama-state-of-the-union-i-want-a-better-politics/, 0.3, ['we', 'need', 'affordable,', 'childcare', 'than', 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1566, 1567, 1568, 1570, 1572, 1575], False, False, False, True
https://www.kansascity.com/opinion/editorials/article7831356.html, 0.3, ['we', 'need', 'affordable,', 'childcare', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [4414, 4415, 4416, 4418, 4420, 4421], False, False, False, True
https://www.elle.com/culture/career-politics/news/a26120/president-obama-delivers-feminist-state-of-the-union/, 0.3, ['we', 'need', 'affordable,', 'childcare', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3855, 3856, 3857, 3859, 3861, 3862], False, False, False, True
http://america.aljazeera.com/articles/2015/1/21/Obama-addresses-sick-and-family-leave-policies.html, 0.25, ['need', 'affordable,', 'than', 'ever.', 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2250, 2251, 2256, 2257, 2259], False, False, False, True
https://hellogiggles.com/lifestyle/state-of-the-union-2/, 0.25, ['we', 'need', 'affordable,', 'childcare', 'than'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3900, 3901, 3902, 3904, 3906], True, False, False, True
https://www.roanoke.com/opinion/commentary/taylor-a-generation-later-how-much-progress-in-nation-s/article_c0dc531b-7768-5363-a03d-36d5ccdadb0b.html, 0.25, ['we', 'need', 'affordable,', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [9032, 9033, 9034, 9039, 9040], False, False, False, True
https://womensagenda.com.au/latest/childcare-is-not-a-nice-to-have-it-s-a-must-have-barack-obama/, 0.25, ['need', 'affordable,', 'childcare', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2038, 2039, 2041, 2043, 2044], False, False, False, True
http://blogs.edweek.org/edweek/campaign-k-12/2015/01/sotu_obama_pitches_college_access.html, 0.25, ['we', 'need', 'affordable,', 'childcare', 'than'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2453, 2454, 2455, 2457, 2459], False, False, False, True
https://www.thetrumpet.com/13977-america-needs-to-change-the-way-it-views-child-care, 0.25, ['we', 'need', 'affordable,', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [874, 875, 876, 881, 882], False, False, False, True
https://grabien.com/story.php?id=20793, 0.2, ['we', 'need', 'than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [792, 793, 800, 801], False, False, False, True
http://america.aljazeera.com/opinions/2015/1/women-need-more-from-president-obama-on-equal-pay.html, 0.2, ['a', 'a', 'president', 'obama'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [4251, 4268, 4284, 4285], False, False, False, True
https://www.eonline.com/news/616773/barack-obama-delivers-state-of-the-union-address-reacts-to-republicans-applause-with-presidential-burn-watch, 0.2, ['we', 'need', 'childcare', 'than'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2133, 2134, 2137, 2139], False, False, False, True
https://www.nowtolove.com.au/news/local-news/barack-obama-focuses-on-womens-rights-in-state-of-the-union-speech-6535, 0.2, ['we', 'need', 'affordable,', 'childcare'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [25468, 25469, 25470, 25489], False, False, False, True
https://www.azquotes.com/quote/885814, 0.15, ['not', 'a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [977, 992, 996], False, False, False, True
https://www.whitehouse.gov/about-the-white-house/presidents/barack-obama/, 0.15, ['a', 'president', 'obama'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1182, 1197, 1198], False, False, False, True
https://www.politifact.com/truth-o-meter/statements/2019/mar/08/donald-trump/did-obamas-white-house-refuse-turn-over-any-docume/, 0.15, ['a', 'a', 'president'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2420, 2448, 2456], False, True, False, True
https://www.foxnews.com/opinion/sony-execs-obama-emails-white-liberal-hypocrisy-revealed-in-all-its-glory, 0.15, ['a', 'president', 'obama'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3872, 3886, 3895], False, False, False, True
https://democracyjournal.org/alcove/barack-obama-and-the-intellectual-as-president/, 0.15, ['not', 'a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1848, 1874, 1877], False, False, False, True
https://insider.foxnews.com/2019/04/09/tucker-carlson-barack-obama-defending-assimilation-immigrants, 0.15, ['we', 'than', 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2874, 2891, 2899], False, False, False, True
https://americablog.com/2013/03/barack-obamas-economic-legacy-his-four-must-have-items.html, 0.15, ['not', 'a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [4151, 4152, 4169], False, False, False, True
https://www.nytimes.com/2019/04/28/us/politics/barack-obama-biden.html, 0.15, ['not', 'a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [13349, 13375, 13381], False, False, False, True
https://news.yahoo.com/video/affordable-childcare-must-obama-035133574.html, 0.15, ['need', 'affordable,', 'childcare'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [6031, 6032, 6045], False, False, False, True
https://barackobama.com/, 0.1, ['president', 'obama'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [74, 75], False, False, False, True
http://www.ontheissues.org/2016/Barack_Obama_Families_+_Children.htm, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [442, 443], False, False, False, True
https://www.realclearpolitics.com/video/2019/04/09/tucker_carlson_its_not_racist_to_say_whats_true_about_immigration_even_obama_and_sanders_admit_that.html, 0.1, ['we', 'than'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1022, 1045], False, False, False, True
https://ktla.com/2019/04/23/obama-boulevard-l-a-to-officially-rename-rodeo-road-during-may-4-ceremony/, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3900, 3908], False, False, False, True
http://www.searchquotes.com/quotation/Its_not_a_nice-to-haveits_a_must-have._Its_time_we_stop_treating_child_care_as_a_side_issue/683273/, 0.1, ['we', 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1680, 1692], False, False, False, True
https://eyeonearlyeducation.com/2015/01/26/president-obamas-child-care-proposal/, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1346, 1347], False, False, False, True
https://www.snopes.com/fact-check/native-son/, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2265, 2273], False, True, False, True
https://www.newsbusters.org/blogs/nb/tom-blumer/2018/04/23/former-ag-mukasey-comey-memos-were-classified-when-written-hillary, 0.1, ['president', 'obama'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [1747, 1748], False, False, False, True
https://www.politico.com/story/2019/04/25/biden-obama-2020-relationship-1287353, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2996, 3015], False, False, False, True
https://www.history.com/topics/us-presidents/barack-obama, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [6906, 6912], False, True, False, True
https://addicted2success.com/quotes/16-powerful-barack-obama-quotes-that-will-inspire-you-to-live-a-great-life/, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [4918, 4919], False, False, False, True
https://www.potus.com/barack-obama/, 0.1, ['a', 'president'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2242, 2259], False, False, False, True
https://www.theguardian.com/world/blog/2011/may/24/barack-obama-uk-state-visit, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [6932, 6938], False, False, False, True
http://www.freerepublic.com/focus/news/2096260/posts, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2224, 2258], False, False, False, True
https://thepoliticalinsider.com/sarah-palin-obama-you-have-no/, 0.1, ['a', 'president'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [4821, 4836], False, False, False, True
http://features.columbiaspectator.com/eye/2017/01/31/a-portrait-of-the-president-as-a-young-man/, 0.1, ['than', 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3914, 3936], False, False, False, True
https://www.youtube.com/watch?v=M7ayvp89h5E, 0.1, ['president', 'obama'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [5175, 5177], False, False, False, True
https://abc7news.com/society/pres-obama-stephen-curry-john-legend-take-part-in-oakland-convention/5145554/, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [5256, 5259], False, False, False, True
https://www.education.com/magazine/article/Obama_Early_Childhood_Education/, 0.1, ['affordable,', 'childcare'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3824, 3846], False, False, False, True
https://www.cheatsheet.com/culture/why-trump-still-resents-obama-so-much.html/, 0.1, ['not', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3911, 3929], False, False, False, True
https://www.blackenterprise.com/michelle-obama-book/, 0.1, ['we', 'than'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2557, 2569], False, False, False, True
https://www.youtube.com/watch?v=MRjmrqatT58, 0.1, ['president', 'obama'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [4337, 4338], False, False, False, True
https://www.sun-sentinel.com/news/politics/fl-ne-barack-obama-gillum-nelson-miami-20181029-story.html, 0.1, ['a', 'president'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [6493, 6509], False, False, False, True
https://www.rgj.com/story/sports/2019/03/21/march-madness-barack-obama-predicts-florida-upset-nevada-basketball/3183149002/, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [9168, 9176], False, False, False, True
https://www.freep.com/story/entertainment/2018/02/18/barack-obama-michelle-obama-presidential-portraits/342972002/, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [9577, 9584], True, False, False, True
https://obamawhitehouse.archives.gov/the-press-office/2015/01/20/remarks-president-barack-obama-prepared-delivery-state-union-address, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [4578, 4579], False, False, False, True
https://en.wikipedia.org/wiki/Barack_Obama_2012_presidential_campaign, 0.1, ["it's", 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [11818, 11819], False, False, False, True
https://slate.com/human-interest/2015/01/state-of-the-union-president-obama-declares-childcare-a-must-have-not-a-women-s-issue.html, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3069, 3101], False, False, False, True
https://www.oprahmag.com/life/relationships-love/g23091965/barack-michelle-obama-pictures/, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [6380, 6390], False, False, False, True
https://www.azquotes.com/author/11023-Barack_Obama, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [7076, 7084], False, False, False, True
https://en.wikipedia.org/wiki/List_of_presidential_trips_made_by_Barack_Obama_(2009), 0.1, ["it's", 'not'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [13145, 13146], False, False, False, True
https://www.nationalreview.com/2019/02/how-congress-can-reclaim-its-power/, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [9000, 9001], False, True, False, True
https://answers.yahoo.com/question/index?qid=20080608004327AAylNz0, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [7963, 7982], False, False, False, True
https://www.orlandoweekly.com/Blogs/archives/2018/10/29/president-obama-will-rally-for-democrats-in-florida-this-friday, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [2795, 2808], False, False, False, True
https://www.biography.com/us-president/barack-obama, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [12030, 12031], False, True, False, True
https://news.yahoo.com/biden-asked-president-obama-not-185324145.html, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [9835, 9871], False, False, False, True
https://www.usatoday.com/story/news/politics/elections/2019/04/25/barack-obama-praises-joe-biden-but-doesnt-offer-2020-endorsement/3571729002/, 0.1, ['we', 'need'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [10115, 10117], False, False, False, True
https://www.yahoo.com/news/topics/barack-obama, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [25960, 25972], False, False, False, True
https://news.yahoo.com/topics/barack-obama, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [25960, 25972], False, False, False, True
http://marquee.blogs.cnn.com/2012/07/06/morgan-freeman-obamas-not-our-first-black-president/, 0.1, ['than', 'ever.'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [27498, 27499], False, False, False, True
https://www.washingtonpost.com/politics/as-joe-biden-seeks-the-obama-mantle-many-obama-loyalists-wait-to-see-who-lights-a-fire/2019/05/11/6ed9beaa-7322-11e9-9f06-5fc2ee80027a_story.html, 0.1, ['a', 'a'], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [3563, 3594], False, False, False, True
https://www.thoughtco.com/barack-obama-president-of-united-states-104366, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
https://www.gq.com/story/donald-trump-undo-obama, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
https://newsone.com/2792224/dinesh-dsouza-barack-obama/, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
https://www.foxnews.com/category/person/barack-obama, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
https://www.answers.com/Q/What_is_Barack_Obama\'s_nickname_in_high_school_and_college, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
https://twitter.com/barackobama, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, True, True
https://www.aol.com/article/news/2017/03/30/where-is-barack-obama-former-president-laying-low-island-writing-book/22018913/, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
https://nypost.com/2017/05/07/inside-baracks-sex-filled-relationships-before-michelle/, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
https://www.facebook.com/barackobama, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, True, True
https://www.washingtonpost.com/sports/2019/03/21/barack-etology-is-back-obama-reveals-his-ncaa-tournament-picks/, 0.0, [], 'we need affordable, highquality childcare mare than ever. it\'s not a nicetohave t\'s a musthave. 111lojqen\' m "florida president obama ', [], False, False, False, True
