--------------------------------------------------
Identified names are: nancy pelosi
--------------------------------------------------
--------------------------------------------------
Query string is: nancy pelosi nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): <urlopen error [Errno 111] Connection refused>
https://www.pinterest.com/pin/205336064241263521/, 0.15, ['nancy', 'pelosi', 'makes'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [1769, 1775, 1800], False, False, False, True
https://truthfeed.com/pelosi-reminds-dems-we-cant-impeach-trump-because-we-dont-like-his-hair/73731/, 0.1, ['we', "can't"], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [1326, 1354], False, False, False, True
https://madworldnews.com/nancy-pelosi-trump-supporters/, 0.1, ['that', 'makes'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [2049, 2050], False, False, False, True
https://www.theatlantic.com/politics/archive/2018/11/why-nancy-pelosi-might-impeach-trump/575560/, 0.1, ['we', 'impeach'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [5675, 5705], False, False, False, True
https://gregfallis.com/category/stupid-fucking-people/, 0.1, ['that', 'makes'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [5049, 5050], False, False, False, True
https://legalinsurrection.com/2018/05/nancy-pelosi-urging-democrats-to-concentrate-on-economic-issues/, 0.1, ['nancy', 'pelosi'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [1490, 1491], False, False, False, True
https://www.usatoday.com/story/news/politics/2019/01/03/nancy-pelosi-admits-nostalgia-george-w-bush-trump-era/2430471002/, 0.1, ['nancy', 'pelosi'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [205, 218], False, False, False, True
https://www.fluther.com/78334/why-do-people-hate-nancy-pelosi-so-much/, 0.1, ['nancy', 'pelosi'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [289, 290], False, False, False, True
https://www.snopes.com/fact-check/nancy-pelosi-removed-treason/, 0.1, ['said', 'that'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [1270, 1308], False, True, False, True
https://lawandcrime.com/opinion/nancy-pelosi-says-trump-isnt-worth-impeaching-and-shes-dead-wrong/, 0.1, ['said', 'something'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [6592, 6604], False, False, False, True
https://www.msn.com/en-ca/news/newspolitics/nancy-pelosi-mueller-doesn%e2%80%99t-have-to-indict-trump-for-congress-to-impeach-him/ar-BBPANFx, 0.1, ['that', 'nancy'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [1220, 1240], False, False, False, True
https://www.pinterest.com/obama4me2/nancy-pelosi-speaker-of-the-house/, 0.1, ['nancy', 'pelosi'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [6810, 6811], False, False, False, True
https://www.businessinsider.my/2019/page/1554/, 0.1, ['that', 'makes'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [12322, 12323], False, False, False, True
https://www.reddit.com/r/EnoughTrumpSpam/comments/a1ibrd/how_donald_trump_appeals_to_men_secretly_insecure/, 0.1, ['that', 'makes'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [12108, 12112], False, False, False, True
https://www.dailymail.co.uk/news/article-6796999/Pelosi-says-Trump-just-not-worth-impeaching.html, 0.1, ['pelosi', 'said'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [5391, 5398], False, False, False, True
https://www.reddit.com/r/politics/comments/annpl9/nancy_pelosis_literal_clapback_at_trump_is_the/, 0.1, ['his', 'hair'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [11115, 11127], False, False, False, True
http://www.floppingaces.net/2018/12/30/i-am-venting-i-need-to-vent-the-liberal-stupidity-is-suffocating/, 0.1, ['that', 'we'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [8116, 8146], True, False, False, True
https://www.balloon-juice.com/2019/03/11/pelosi-trumps-not-worth-impeaching/, 0.1, ['that', 'makes'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [17569, 17570], False, False, False, True
http://nymag.com/intelligencer/2019/03/why-pelosis-anti-impeachment-stand-makes-sense.html, 0.1, ['said', 'something'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [23556, 23583], False, False, False, True
https://www.dailymail.co.uk/news/article-6558883/Trump-says-asked-Nancy-Pelosi-Democrats-dont-use-shutdown-impeach-him.html, 0.1, ['that', 'nancy'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [5053, 5070], False, False, False, True
https://democraticunderground.com/10029069752, 0.1, ['we', 'impeach'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [28458, 28474], False, False, False, True
https://www.foxnews.com/transcript/sen-graham-slams-nancy-pelosi-for-being-absurd-petty-and-shameful, 0.1, ['nancy', 'pelosi'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [1720, 1721], False, False, False, True
https://www.newyorker.com/news/our-columnists/what-pelosi-meant-impeaching-trump-hes-just-not-worth-it, 0.1, ['that', 'makes'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [61501, 61503], False, False, False, True
http://nymag.com/intelligencer/2017/06/every-terrifying-thing-that-donald-trump-has-done.html, 0.1, ['nancy', 'pelosi'], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [32048, 32049], False, True, False, True
https://www.politico.com/magazine/story/2017/11/02/nancy-pelosi-house-democratic-leader-profile-feature-2017-215759, 0.0, [], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [], False, False, False, True
https://www.lucianne.com/thread.aspx/?artnum=966458, 0.0, [], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [], False, False, False, True
http://sandrarose.com/2019/01/capitol-hill-braces-for-full-govt-shutdown-democrats-vow-revenge-for-canceling-pelosi-trip-resign-now-or-be-impeached/, 0.0, [], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [], False, False, False, True
https://lucianne.com/thread.aspx/?artnum=966315&Reply_Id=11964880, 0.0, [], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [], False, False, False, True
https://democraticunderground.com/100211453397, 0.0, [], "nancy pelosi accidentally said something that makes sense: nancy pelosi: we can't impeach trump just because we dislike his hair ", [], False, False, False, True
