--------------------------------------------------
Identified names are: nancy pelosi
--------------------------------------------------
--------------------------------------------------
Query string is: nancy pelosi nhat we saw in those rooms was lal dazzling, sparkling, array of god's children worthy of respect." nancy pelosi lifefirst www.tupycolll
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
http://www.burtprelutsky.com/2009/12/new-and-improved-iron-curtain.html, 0.14285714285714285, ['in', 'of', 'of'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [2599, 2610, 2632], False, False, False, False
https://www.weaselzippers.us/353903-pelosis-dad-once-praised-the-lives-of-robert-e-lee-and-stonewall-jackson-at-statue-dedication/, 0.09523809523809523, ['of', 'of'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [303, 318], False, False, False, True
https://www.cliffsnotes.com/literature/d/dubliners/summary-and-analysis/eveline/eveline-1, 0.09523809523809523, ['in', 'those'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [2417, 2428], False, False, False, False
https://www.shmoop.com/catcher-in-the-rye/chapter-16-quotes-2.html, 0.09523809523809523, ['in', 'was'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [2353, 2387], False, False, False, False
https://www.coursehero.com/tutors-problems/Psychology/9814192-Worry-Jack-is-concerned-that-Nancy-and-Noel-wont-do-well-in-the-absen/, 0.09523809523809523, ['in', 'was'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [587, 606], False, False, False, True
http://www.fiction.us/stratton/land/chap4.html, 0.09523809523809523, ['of', 'nancy'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [5429, 5444], False, False, False, True
https://www.brainyquote.com/quotes/eric_cantor_412014, 0.09523809523809523, ['of', 'of'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [3063, 3077], False, False, False, True
https://www.enotes.com/homework-help/explain-statement-we-believed-she-had-do-which-had-216215, 0.09523809523809523, ['was', 'of'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [3071, 3093], False, False, False, False
https://obamawhitehouse.archives.gov/the-press-office/2014/11/21/remarks-president-immigration, 0.09523809523809523, ['nancy', 'pelosi'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [6096, 6097], False, False, False, True
https://www.litcharts.com/lit/a-rose-for-emily/characters/miss-emily-s-father, 0.09523809523809523, ['in', 'was'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [3326, 3331], False, False, False, False
https://brainly.com/question/4080902, 0.09523809523809523, ['in', 'was'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [2753, 2758], False, False, False, False
https://www.rt.com/uk/411328-tree-man-fight-leicester/, 0.09523809523809523, ['in', 'was'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [2259, 2289], False, False, False, False
https://www.reddit.com/r/The_Donald/comments/7zao5y/libs_hes_a_raging_lunatic_hes_lost_all_touch_with/, 0.09523809523809523, ['nancy', 'pelosi'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [7945, 7946], False, False, False, True
https://www.news-medical.net/news/20170921/Open-your-mouth-and-say-goo-goo-Dentists-treating-ever-younger-patients.aspx, 0.09523809523809523, ['of', 'children'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [3455, 3458], False, False, False, False
http://www.foxella.com/so-to-those-who-saw-a-conspiracy-including-a-member-of-her-family-who-expressed-as-such-i-am-here-to-say-that-there-was-nothing/, 0.09523809523809523, ['in', 'was'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [5967, 6002], False, False, False, False
https://blog.prx.org/2016/06/chasing-hillary-rodham/, 0.09523809523809523, ['we', 'saw'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [1958, 1959], False, False, False, True
https://www.theodysseyonline.com/black-slurs-through-white-teeth-racism-classroom, 0.09523809523809523, ['of', 'children'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [20690, 20694], False, False, False, False
https://www.reddit.com/r/ShitPoliticsSays/comments/7zyfgv/melania_will_never_rise_to_the_mantle_of_first/, 0.09523809523809523, ['of', 'worthy'], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [28331, 28343], False, False, False, False
https://www.brainyquote.com/quotes/tim_ryan_792387, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, True
https://www.studyblue.com/notes/note/n/quiz-8/deck/11589724, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, False
https://www.shmoop.com/white-teeth/teeth-symbol.html, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, False
https://ebible.com/nkjv/section/1573, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, False
https://newrepublic.com/article/140869/will-trump-era-finally-kill-paul-ryans-wonkish-cred, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, True
https://www.pinterest.com/pin/417357090460350483/, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, False
https://twitter.com/realjameswoods/status/955276835826253830, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, True
https://brainly.com/question/3809202, 0.0, [], 'nhat we saw in those rooms was lal dazzling, sparkling, array of god\'s children worthy of respect." nancy pelosi lifefirst www.tupycolll ', [], False, False, False, False
