--------------------------------------------------
Identified names are: 
--------------------------------------------------
--------------------------------------------------
Query string is:  how do you tell a communist? well, someone who reajs ahin.und you tell someone who
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): <urlopen error [Errno -2] Name or service not known>
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
https://www.ar15.com/forums/General/Rudy-Giuliani-gets-booed-at-Yankee-Stadium/5-2114704/, 0.8947368421052632, ['how', 'do', 'you', 'tell', 'a', 'communist?', 'well,', 'someone', 'who', 'you', 'tell', 'someone', 'who', 'understands', 'marx', 'and', 'lenin.'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [2762, 2763, 2764, 2765, 2766, 2767, 2768, 2770, 2771, 2779, 2780, 2784, 2785, 2786, 2787, 2788, 2789], False, False, False, True
https://www.fluentu.com/blog/german/funny-german-sayings/, 0.10526315789473684, ['tell', 'who'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [2223, 2235], False, False, False, True
https://en.wikipedia.org/wiki/Asian_people, 0.10526315789473684, ['you', 'and'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [9226, 9234], False, False, False, True
https://www.youtube.com/watch?v=7wa1EakS-w4, 0.10526315789473684, ['who', 'and'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [3398, 3436], False, False, False, True
https://www.wikihow.com/Gain-Fat, 0.10526315789473684, ['a', 'who'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [9902, 9907], False, False, False, True
https://matzav.com/the-matzav-shmoooze-two-possible-solutions-to-the-shidduch-crisis-the-theoretical-one-and-the-practical-one/, 0.10526315789473684, ['you', 'tell'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [10634, 10638], False, False, False, True
https://www.buzzfeed.com/, 0.10526315789473684, ['a', 'who'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [14580, 14598], False, False, False, True
https://www.reddit.com/r/arabs/comments/6y1wod/what_are_some_cultural_differences_between_the/, 0.10526315789473684, ['someone', 'who'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [9462, 9463], False, False, False, True
https://www.scribd.com/document/181602041/The-Iron-Warrior-Volume-21-Issue-7, 0.10526315789473684, ['you', 'and'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [25413, 25432], False, False, False, True
https://www.reddit.com/r/kpop/comments/413lcg/chinese_weibo_reaction_on_tzuyus_apology/, 0.10526315789473684, ['a', 'well,'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [13514, 13526], False, False, False, True
https://www.cliffsnotes.com/cliffsnotes/subjects/writing/what-s-the-difference-between-like-and-such-as, 0.10526315789473684, ['you', 'tell'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [12407, 12408], False, False, False, True
https://www.youtube.com/channel/UCwdo8-3UrfZ9scHPl0m4Ysg, 0.10526315789473684, ['a', 'who'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [21848, 21858], False, False, False, True
http://archive.org/stream/languageculture22marc/languageculture22marc_djvu.txt, 0.10526315789473684, ['a', 'someone'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [33766, 33777], False, False, False, True
https://www.goodreads.com/book/show/8913542-23-things-they-don-t-tell-you-about-capitalism, 0.10526315789473684, ['you', 'tell'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [5333, 5343], False, False, False, True
http://docshare.tips/pagan-amp-christian-creeds-origins-and-meaning-carpenter-1921_5850f1f7b6d87faea78b56f9.html, 0.10526315789473684, ['you', 'who'], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [126351, 126362], False, False, False, True
https://www.issuu.com/plu-archives/docs/mast_1947-1948, 0.0, [], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [], False, False, False, True
https://epdf.tips/yiddish-language-and-culture-then-and-now.html, 0.0, [], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [], False, False, False, True
https://en.wikipedia.org/wiki/Template_talk:Jewish_outreach, 0.0, [], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [], False, False, False, True
https://archive.org/stream/The_Times_News_Idaho_Newspaper_1965_01_17/The_Times_News_Idaho_Newspaper_1965_01_17_djvu.txt, 0.0, [], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [], False, False, False, True
https://peacehistory-usfp.org/vietnam-war/, 0.0, [], 'how do you tell a communist? well, someone who reajs ahin.und you tell someone who understands marx and lenin.', [], False, False, False, True
