--------------------------------------------------
Identified names are: 
--------------------------------------------------
--------------------------------------------------
Query string is:  reduces rograms, oncljnchd, never disappear
--------------------------------------------------


--------------------------------------------------
Query string is:  actually, a government bij eau is the nearest thing to eternal eewe'lftve e his earth." ron
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
https://www.courierpress.com/story/opinion/columnists/2017/03/15/thomas-opportunity-cut-big-government/99204800/, 0.5714285714285714, ['reduces', 'never', 'disappear.', 'actually,', 'a', 'government', 'is', 'the', 'nearest', 'thing', 'to', 'eternal'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [6755, 6763, 6764, 6765, 6766, 6767, 6769, 6770, 6771, 6772, 6773, 6774], False, False, False, True
https://www.facebook.com/markrhudson, 0.5714285714285714, ['reduces', 'never', 'disappear.', 'actually,', 'a', 'government', 'is', 'the', 'nearest', 'thing', 'to', 'eternal'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1557, 1565, 1566, 1567, 1568, 1569, 1571, 1572, 1573, 1574, 1575, 1576], False, False, False, True
https://www.brainyquote.com/quotes/ronald_reagan_147680, 0.19047619047619047, ['never', 'disappear.', 'actually,', 'a'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [149, 150, 151, 152], False, False, False, True
https://www.sciencedaily.com/releases/2015/07/150702163902.htm, 0.19047619047619047, ['a', 'is', 'the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1068, 1075, 1076, 1084], False, False, False, True
http://thinkexist.com/quotation/no_government_ever_voluntarily_reduces_itself_in/322405.html, 0.19047619047619047, ['never', 'disappear.', 'actually,', 'a'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [64, 65, 66, 67], False, False, False, True
https://www.fourfourtwo.com/news/my-desire-defy-critics-will-never-disappear-says-henderson, 0.19047619047619047, ['a', 'is', 'the', 'thing'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [2413, 2448, 2449, 2451], False, False, False, True
https://www.goodreads.com/quotes/149332-no-government-ever-voluntarily-reduces-itself-in-size-government-programs, 0.19047619047619047, ['never', 'disappear.', 'actually,', 'a'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1906, 1907, 1908, 1909], False, False, False, True
https://answers.microsoft.com/en-us/windows/forum/windows_10-start/programs-missing-from-start-menu-windows-10/1de9b3fe-d994-48c0-9b9a-18f6991d44eb, 0.19047619047619047, ['a', 'is', 'the', 'thing'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [5670, 5705, 5707, 5709], False, False, False, True
https://en.wikipedia.org/wiki/B.C.E., 0.19047619047619047, ['is', 'the', 'to', 'his'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [8085, 8095, 8104, 8110], False, False, False, True
http://www.greatdreams.com/eridanus.htm, 0.19047619047619047, ['a', 'is', 'the', 'nearest'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [10640, 10646, 10660, 10661], False, False, False, True
https://www.pinterest.com/pd0642/space/, 0.19047619047619047, ['the', 'nearest', 'to', 'his'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [22417, 22423, 22425, 22455], False, False, False, True
https://aspe.hhs.gov/basic-report/review-family-preservation-and-family-reunification-programs, 0.19047619047619047, ['a', 'is', 'the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [34388, 34402, 34404, 34423], False, False, False, True
https://weldingweb.com/showthread.php?241441-What-size-generator-to-run-syncrowave, 0.14285714285714285, ['never', 'disappear.', 'actually,'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [2663, 2664, 2665], False, False, False, True
https://www.technipages.com/windows-enable-disable-user-account-control-uac, 0.14285714285714285, ['a', 'is', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [2193, 2206, 2223], False, False, False, True
https://learn.eartheasy.com/guides/compost-tumblers/, 0.14285714285714285, ['a', 'is', 'the'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [5133, 5158, 5164], False, False, False, True
https://brainly.com/question/2605561, 0.14285714285714285, ['is', 'the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [3912, 3946, 3953], False, False, False, True
https://brainly.com/question/457230, 0.14285714285714285, ['a', 'is', 'the'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [3323, 3339, 3362], False, False, False, True
https://www.biblegateway.com/passage/?search=2+Corinthians+2%3A5-6%3A13&version=TLB, 0.14285714285714285, ['the', 'to', 'eternal'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [7707, 7712, 7729], False, False, False, True
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2995716/, 0.14285714285714285, ['the', 'to', 'his'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [6733, 6763, 6769], False, False, False, True
https://www.britannica.com/science/evolution-scientific-theory/The-science-of-evolution, 0.14285714285714285, ['the', 'to', 'e'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [29958, 29978, 29986], False, False, False, True
https://www.brainyquote.com/quotes/jeffrey_r_immelt_643681, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [2804, 2816], False, False, False, True
https://www.msn.com/en-in/lifestyle/smart-living/25-jobs-that-will-never-disappear/ss-BBSzNcZ, 0.09523809523809523, ['is', 'the'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [709, 712], False, False, False, True
https://www.tcarta.com/blog/589/, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1004, 1026], False, False, False, True
https://www.apnews.com/0c47d7ffa7a24759987630ab07281a7e, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [3333, 3339], False, False, False, True
https://genius.com/Original-broadway-cast-of-dear-evan-hansen-disappear-lyrics, 0.09523809523809523, ['is', 'the'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [4980, 4994], False, False, False, True
https://en.wikipedia.org/wiki/Captive_breeding, 0.09523809523809523, ['is', 'the'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [7168, 7171], False, False, False, True
https://www.reuters.com/article/us-usa-trump-budget-idUSKBN16M1DO, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [8992, 9000], False, False, False, True
https://www.youtube.com/watch?v=sSxT8E9Ls5c, 0.09523809523809523, ['never', 'disappear.'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1445, 1446], False, False, False, True
https://news.mongabay.com/2016/10/environmentalists-squirm-as-jokowi-eyes-lake-toba-tourism-bonanza/, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [4322, 4325], False, False, False, True
https://www.sciencelearn.org.nz/videos/358-water-distribution, 0.09523809523809523, ['a', 'government'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1797, 1798], False, False, False, True
https://countercurrents.org/2017/06/15/what-on-earth-is-a-human-being/, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [5230, 5233], False, False, False, True
https://reason.com/blog/2010/03/31/the-nearest-thing-to-eternal-l, 0.09523809523809523, ['a', 'government'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1701, 1702], False, False, False, True
https://www.reddit.com/r/rollercoasters/comments/7edv9q/massive_construction_right_behind_apocalypse_at/, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [11915, 11920], True, False, False, True
http://acecomments.mu.nu/?post=380975, 0.09523809523809523, ['to', 'eternal'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [15372, 15373], False, False, False, True
https://us.norton.com/internet-security, 0.09523809523809523, ['a', 'is'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [21536, 21562], False, False, False, True
https://gizmodo.com/what-would-happen-if-you-actually-walked-on-the-sun-1797034559, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [24855, 24860], False, False, False, True
https://wamu.org/story/17/09/01/district-extends-deadline-taxicab-transition-digital-meters/, 0.09523809523809523, ['the', 'thing'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [14831, 14836], False, False, False, True
https://www.dailymail.co.uk/news/article-3162563/The-dying-giant-species-grave-world-s-male-white-rhino-certain-never-mate-lives-guard-protect-poachers.html, 0.09523809523809523, ['the', 'thing'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [10186, 10222], False, False, False, True
https://www.pinterest.com/deesohana/preschool-e-is-for-earth/, 0.09523809523809523, ['a', 'is'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [25311, 25328], False, False, False, True
https://archive.org/stream/dailycolonist0323uvic_51/dailycolonist0323uvic_51_djvu.txt, 0.09523809523809523, ['the', 'nearest'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [69844, 69845], False, False, False, True
https://www.facebook.com/What.If.science/videos/2472353256323313/, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [1847, 1853], False, False, False, True
https://www.loot.co.za/index/html/index4434.html, 0.09523809523809523, ['the', 'to'], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [113903, 113906], False, False, False, True
https://www.studyblue.com/notes/note/n/biology-final/deck/18516890, 0.0, [], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [], False, False, False, True
https://www.youtube.com/watch?v=LOulCAz4S0M, 0.0, [], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [], False, False, False, True
https://www.reddit.com/r/NoStupidQuestions/comments/3tmmyp/have_we_discovered_every_piece_of_land_on_earth/, 0.0, [], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [], False, False, False, True
https://scholarlycommons.law.northwestern.edu/cgi/viewcontent.cgi?article=7549&context=jclc, 0.0, [], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [], False, False, False, True
https://www.researchgate.net/publication/225897176_Loop_Parallelization_Algorithms, 0.0, [], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [], False, False, False, True
https://www.researchgate.net/publication/323371311_Do_High_Quality_Kindergarten_and_First_Grade_Classrooms_Mitigate_Preschool_Fadeout, 0.0, [], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [], False, False, False, True
https://economictimes.indiatimes.com/slideshows/science-technology/you-can-actually-see-iss-with-your-own-eyes-from-earth/the-map/slideshow/56760594.cms, 0.0, [], 'reduces rograms, oncljnchd, never disappear. actually, a government bij eau is the nearest thing to eternal eewe\'lftve e his earth." ron ', [], False, False, False, True
