--------------------------------------------------
Identified names are: michele bachmann
--------------------------------------------------
--------------------------------------------------
Query string is: michele bachmann bonestt have been buried for millions of why are they so clean when they're in
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
https://www.snopes.com/fact-check/bachmann-dinosaur-bones/, 0.8, ['have', 'been', 'buried', 'for', 'millions', 'of', 'why', 'are', 'they', 'so', 'clean', 'when', 'in', 'museums?', 'they', 'would', 'be', 'dirty.', 'and', 'if'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [1171, 1172, 1173, 1174, 1175, 1176, 1179, 1180, 1181, 1182, 1183, 1184, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193], False, True, False, True
https://mountainmystery.com/tag/garden-of-eden/, 0.44, ['have', 'been', 'buried', 'for', 'of', 'why', 'are', 'they', 'so', 'clean', 'when'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [1281, 1282, 1283, 1284, 1286, 1289, 1290, 1291, 1292, 1293, 1294], False, False, False, True
https://mountainmystery.com/2015/06/04/michele-bachmanns-dirty-bones/, 0.4, ['have', 'been', 'buried', 'for', 'of', 'why', 'are', 'they', 'so', 'clean'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [1388, 1389, 1390, 1391, 1393, 1396, 1397, 1398, 1399, 1400], False, False, False, True
https://conservativememes.com/t/stupid-humans, 0.4, ['been', 'buried', 'for', 'of', 'why', 'they', 'so', 'clean', 'when', "they're"], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [5311, 5312, 5313, 5315, 5318, 5320, 5321, 5322, 5323, 5352], True, False, False, True
https://claytoonz.com/tag/english/, 0.28, ['millions', 'of', 'why', 'are', 'they', 'so', 'clean'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [1169, 1170, 1174, 1175, 1176, 1177, 1178], False, False, False, True
https://claytoonz.com/2015/09/07/speak-american/, 0.28, ['millions', 'of', 'why', 'are', 'they', 'so', 'clean'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [1356, 1357, 1361, 1362, 1363, 1364, 1365], False, False, False, True
https://forum.prisonplanet.com/index.php?topic=215051.0, 0.16, ['for', 'and', 'if', 'the'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [296, 302, 313, 322], False, False, False, False
https://www.amren.com/news/2011/09/bachmann_claims/, 0.16, ['in', 'they', 'would', 'be'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [19065, 19074, 19112, 19113], False, False, False, True
https://www.cnbc.com/2019/05/02/amy-klobuchar-american-economy-needs-to-rebalanced.html?&qsearchterm=klobuchar, 0.12, ['why', 'are', 'they'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [4245, 4250, 4269], False, False, False, True
http://transcripts.cnn.com/TRANSCRIPTS/1011/22/acd.02.html, 0.08, ['of', 'why'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [7136, 7140], False, False, False, True
http://transcripts.cnn.com/TRANSCRIPTS/1103/08/ltm.01.html, 0.08, ['of', 'why'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [6371, 6375], False, False, False, True
http://religion.blogs.cnn.com/2011/06/27/michele-bachmann-as-evangelical-feminist/comment-page-25/, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [2332, 2334], False, False, False, True
http://religion.blogs.cnn.com/2011/07/15/michele-bachmann-officially-leaves-her-church/comment-page-18/, 0.08, ['so', 'when'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [5984, 5991], False, False, False, True
https://skydancingblog.com/tag/michelle-bachman/, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [1533, 1534], False, False, False, True
http://abcnewsradioonline.com/politics-news/tag/jay-leno, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [3611, 3612], False, False, False, True
https://www.wsj.com/video/opinion-journal-off-to-the-races/C77D10A1-C345-4004-99C7-6FE024440305.html, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [794, 795], False, False, False, True
http://caffertyfile.blogs.cnn.com/2011/07/18/when-it-comes-to-the-gay-community-is-michele-bachmann-living-in-the-twilight-zone/, 0.08, ['of', 'why'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [13981, 13988], False, False, False, True
https://www.wsj.com/video/am-reportjobs-news-401-k-snafu-romney-vs-obama/39221AD7-2E2A-4BA2-8EBF-F32B558C4C6C.html, 0.08, ['they', 'would'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [9066, 9075], False, False, False, True
http://afflictor.com/tag/sarah-palin/, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [3626, 3643], False, False, False, True
https://www.gardenweb.com/discussions/2267776/should-the-wwii-vets-get-special-access-to-the-shut-down-memorial, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [8985, 8986], False, False, False, True
https://www.dailymail.co.uk/news/article-2334063/Democrat-Jim-Graves-nearly-beat-Michele-Bachmann-wont-run-year-shes-bowed-race-saying-Mission-Accomplished.html, 0.08, ['of', 'why'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [4449, 4470], False, False, False, True
https://brownsvilleherald-tribune.blogspot.com/2011/06/in-ditzy-michele-bachman-republican.html, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [24333, 24334], False, False, False, True
https://freethoughtblogs.com/pharyngula/2011/09/14/michele-bachmann-pseudo-scientist-and-anti-vaxxer/, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [22939, 22941], False, False, False, True
https://margaretandhelen.com/2011/07/26/peace-and-quiet-for-michele-bachmann/, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [15703, 15704], False, True, False, True
https://www.democraticunderground.com/10023802775, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [8141, 8142], False, False, False, True
https://www.repealcreationism.com/508/17-year-old-to-michelle-bachmann-show-me-your-nobel-laureate-scientists/, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [41288, 41289], False, True, False, True
https://www.pinterest.com/michelebachmann/, 0.08, ['have', 'been'], "bonestt have been buried for millions of why are they so clean when they're in museums? they would be dirty. and if the dinosaur bonesare ", [58674, 58675], False, False, False, True
