--------------------------------------------------
Identified names are: winston churchill
--------------------------------------------------
--------------------------------------------------
Query string is: winston churchill people will accept your ideas more readly f you attrbute them to mark twain..
--------------------------------------------------


--------------------------------------------------
Query string is: winston churchill font is also crucial" winston churchill
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
http://davidvanalstyne.com/pg-quotesgeneral.html, 0.4, ['people', 'will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1767, 1768, 1769, 1770, 1771, 1773, 1776, 1778], False, False, False, True
http://www.jimpoz.com/quotes/Category:Quotations, 0.35, ['will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [410, 411, 412, 413, 415, 418, 420], False, False, False, True
http://www.jimpoz.com/quotes/Speaker:Unknown/Page:16, 0.35, ['will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [174, 175, 176, 177, 179, 182, 184], False, False, False, True
http://www.quotationspage.com/subjects/quotations/, 0.35, ['will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1441, 1442, 1443, 1444, 1446, 1449, 1451], False, False, False, False
https://answers.yahoo.com/question/index?qid=20070713123407AA8fIaD, 0.35, ['will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4941, 4942, 4943, 4944, 4946, 4949, 4951], False, False, False, True
http://www.langston.com/Fun_People/1995/1995ABU.html, 0.35, ['will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3636, 3637, 3638, 3639, 3641, 3644, 3646], False, False, False, True
https://answers.yahoo.com/question/index?qid=20070707151039AAmHSBj, 0.35, ['will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [227, 228, 229, 230, 232, 235, 237], False, False, False, True
https://darkcomedy-alan.blogspot.com/2010/03/, 0.35, ['will', 'accept', 'your', 'ideas', 'more', 'you', 'them'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3899, 3900, 3901, 3902, 3903, 3906, 3908], False, False, False, True
https://www.fanfiction.net/s/5652064/1/Funny-Quotes, 0.25, ['will', 'accept', 'your', 'ideas', 'more'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1226, 1227, 1228, 1229, 1231], False, False, False, True
https://uk.ambafrance.org/New-French-lycee-named-in-honour-of-Winston-Churchill, 0.25, ['to', 'is', 'also', 'winston', 'churchill'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1371, 1376, 1377, 1402, 1403], False, False, False, True
http://www-personal.umich.edu/~bryantwu/archer/saywhat/, 0.25, ['people', 'will', 'accept', 'your', 'ideas'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [236, 237, 238, 239, 240], False, False, False, True
https://dan.hersam.com/all-quotes.html, 0.2, ['will', 'accept', 'your', 'ideas'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [2461, 2462, 2463, 2464], False, False, False, True
https://www.thecompanyrocks.com/category/quotations/, 0.2, ['will', 'accept', 'your', 'ideas'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3253, 3254, 3255, 3256], False, False, False, True
https://www.washingtonpost.com/archive/entertainment/books/1980/03/02/churchills-little-assassin/e5a35279-fa89-4829-b269-12acfb18d78c/, 0.2, ['to', 'is', 'winston', 'churchill'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1818, 1839, 1857, 1858], False, False, False, True
https://www.amazon.com/Winston-Churchill-World-Collection-Book/dp/B00XJ06SQI, 0.15, ['you', 'to', 'is'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [156, 164, 179], False, False, False, True
https://spectator.org/the-churchill-marriage-and-lady-castlerosse/, 0.15, ['people', 'will', 'you'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4611, 4622, 4628], False, False, False, True
https://people.eou.edu/bgrigsby/stuff/quotes/, 0.15, ['people', 'will', 'accept'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4623, 4624, 4625], False, False, False, True
https://www.answers.com/Q/What_was_Winston_churchills_dislikes, 0.1, ['you', 'to'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [35, 38], False, False, False, True
https://townhall.com/tipsheet/cortneyobrien/2018/03/06/gary-oldman-was-criticized-for-thanking-winston-churchill-in-his-acceptance-speech-n2457894, 0.1, ['winston', 'churchill'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3436, 3437], False, False, False, True
https://www.historyonthenet.com/winston-churchill-life, 0.1, ['more', 'to'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3142, 3176], False, False, False, True
http://www.bbcamerica.com/anglophenia/2015/04/50-churchill-quotes/, 0.1, ['winston', 'churchill'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4027, 4028], False, False, False, True
https://en.wikipedia.org/wiki/Death_and_funeral_of_Winston_Churchill, 0.1, ['to', 'mark'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1344, 1345], False, False, False, True
https://www.smithsonianmag.com/history/winston-churchills-historic-fight-them-beaches-speech-wasnt-heard-public-until-after-wwii-180967278/, 0.1, ['will', 'more'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3885, 3914], False, False, False, True
https://winstonchurchill.hillsdale.edu/fake-history-in-churchill-starring-brian-cox/, 0.1, ['to', 'mark'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3120, 3126], False, False, False, True
https://www.commentarymagazine.com/articles/winston-churchill-retorts-and-all/, 0.1, ['is', 'also'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4310, 4311], False, False, False, True
https://www.pinterest.com/pin/308918855668413326/, 0.1, ['to', 'is'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4158, 4164], False, False, False, True
https://mengsyn.com/quotes-for-my-kids/, 0.1, ['more', 'you'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1698, 1738], False, False, False, True
https://www.positivityblog.com/winston-churchill/, 0.1, ['people', 'will'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [2370, 2379], False, False, False, True
https://www.pinterest.com/pin/438749188697117195/, 0.1, ['to', 'is'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4571, 4577], False, False, False, False
https://www.thesun.co.uk/news/5567146/winston-churchill-war-rooms-never-before-seen-photos-defeat-nazis/, 0.1, ['is', 'also'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1937, 1957], False, False, False, True
https://exonews.org/how-winston-churchills-views-on-aliens-were-revealed-in-lost-letter/, 0.1, ['also', 'winston'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1530, 1556], False, False, False, True
https://winstonchurchill.hillsdale.edu/churchill-presidents-franklin-roosevelt/, 0.1, ['them', 'to'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4016, 4041], False, False, False, True
https://winstonchurchill.org/publications/finest-hour/finest-hour-183/sarah-churchill-winstons-right-hand-man/, 0.1, ['is', 'winston'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4968, 4982], False, False, False, True
http://news.shmarketingdesign.com/following-the-trail-of-winston-churchill/, 0.1, ['to', 'is'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [1160, 1196], False, False, False, True
https://www.theamericanconservative.com/articles/time-to-remember-all-of-churchills-moments/, 0.1, ['to', 'is'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [4278, 4284], False, False, False, True
https://winstonchurchill.org/publications/finest-hour/finest-hour-176/jack-churchill-faithful-brother/, 0.1, ['is', 'winston'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [5037, 5051], False, False, False, True
https://www.businessinsider.com/success-quotes-from-accomplished-people-2014-9, 0.1, ['is', 'also'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [11605, 11625], False, False, False, True
https://www.nationalreview.com/2018/05/winston-churchill-ancestor-duke-of-marlborough-soldiers-strategies/, 0.1, ['people', 'more'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [7404, 7421], False, True, False, True
https://www.nationalgeographic.com/culture/2019/01/allies-roosevelt-churchill-stalin-won-world-war-II/, 0.1, ['also', 'churchill'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [13362, 13381], False, False, False, True
https://www.jihadwatch.org/2017/05/why-are-the-loudest-proponents-of-tolerance-and-peace-so-frequently-ugly-hateful-people, 0.1, ['your', 'more'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [3503, 3511], False, False, False, True
http://unclejoebenson.net/quotes.htm, 0.1, ['your', 'ideas'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [11868, 11871], False, False, False, True
http://www.quotegarden.com/quotations.html, 0.1, ['will', 'accept'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [7363, 7364], False, False, False, True
https://www.thedailybeast.com/when-winston-churchill-embodied-keep-calm-and-carry-on, 0.1, ['winston', 'churchill'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [31601, 31602], False, False, False, True
http://www.blue-n-gold.com/halfdan/favquotes.htm, 0.1, ['is', 'also'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [17866, 17867], False, False, False, True
https://www.goodreads.com/book/show/38470102-churchill, 0.1, ['to', 'mark'], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [27114, 27118], False, False, False, True
https://www.history.com/topics/british-history/winston-churchill, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, True, False, True
https://susaneliamacneal.blogspot.com/2009/09/churchills-staffs-typewriters.html, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
https://ethw.org/Winston_Churchill, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
https://www.iwm.org.uk/history/how-churchill-led-britain-to-victory-in-the-second-world-war, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
https://www.thetrumpet.com/16822-anniversary-of-the-death-of-winston-churchill-the-man-who-saved-western-civilization, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
https://www.azquotes.com/author/2886-Winston_Churchill, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
https://www.truthdig.com/articles/winston-churchills-perverse-place-in-the-american-imagination/, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
https://anetizen.blogspot.com/2014/, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
http://mediafiles.pragmaticmarketing.com/Framework-Files/quotes1307_6-24-13.pptx, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, False
https://en.wikipedia.org/wiki/Winston_Churchill, 0.0, [], 'people will accept your ideas more readly f you attrbute them to mark twain... font is also crucial" winston churchill ', [], False, False, False, True
