--------------------------------------------------
Identified names are: 
--------------------------------------------------
--------------------------------------------------
Query string is:  allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
https://www.reference.com/government-politics/main-characteristics-democracies-c57076cdb9ece546, 0.20689655172413793, ['allow', 'to', 'the', 'of', 'countries', 'in'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [3212, 3218, 3232, 3235, 3245, 3257], False, False, False, True
https://www.thenation.com/article/abolish-police-instead-lets-have-full-social-economic-and-political-equality/, 0.13793103448275862, ['and', 'have', 'people', 'like'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [4103, 4121, 4128, 4131], False, False, False, True
https://sites.duke.edu/krishna/files/2013/10/Poverty-and-Democratic-Participation-Reconsidered.doc, 0.13793103448275862, ['the', 'of', 'that', 'in'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [3886, 3895, 3915, 3916], False, False, False, True
https://www.democracynow.org/topics/right_livelihood_award/2, 0.13793103448275862, ['the', 'livelihood', 'of', 'that'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1532, 1534, 1558, 1563], False, False, False, True
https://www.democracynow.org/2010/9/15/right_livelihood_award_celebrates_30th_anniversary, 0.13793103448275862, ['the', 'livelihood', 'of', 'in'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [2176, 2179, 2212, 2226], False, False, False, True
http://business.time.com/2010/11/05/is-democracy-necessary-for-economic-success/, 0.10344827586206896, ['the', 'of', 'that'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1858, 1866, 1878], False, False, False, True
https://fee.org/articles/democracy-cant-really-be-democratic/, 0.10344827586206896, ['of', 'that', 'in'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1236, 1280, 1292], False, False, False, True
http://hdr.undp.org/en/content/human-development-about-putting-people-center, 0.10344827586206896, ['of', 'that', 'in'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [717, 722, 772], False, False, False, True
https://www.weforum.org/agenda/2015/05/9-mega-trends-shaping-the-future-of-africa/, 0.10344827586206896, ['to', 'defend', 'by'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1503, 1504, 1523], False, False, False, True
https://freedomhouse.org/article/democracies-human-rights-and-collective-action, 0.10344827586206896, ['the', 'of', 'countries'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [5040, 5042, 5045], False, False, False, True
https://www.sciencedirect.com/science/article/pii/S0264999310002269, 0.10344827586206896, ['by', 'the', 'of'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1502, 1520, 1523], False, False, False, True
https://www.nytimes.com/2004/01/31/books/on-the-dark-side-of-democracy.html, 0.10344827586206896, ['and', 'free', 'markets'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [3757, 3800, 3801], False, False, False, True
https://www.brookings.edu/opinions/dilemmas-of-democracy-and-state-power-in-africa/, 0.10344827586206896, ['the', 'of', 'countries'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [14416, 14422, 14432], False, False, False, True
https://www.opendemocracy.net/ioan-m-lewis/somalia-livelihood-and-politics/, 0.10344827586206896, ['have', 'and', 'have'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [2936, 2947, 2952], False, False, False, True
https://www.cambridge.org/core/journals/american-political-science-review/article/some-social-requisites-of-democracy-economic-development-and-political-legitimacy1/26559429359F42D3E9B8BC82CA65546A, 0.10344827586206896, ['to', 'defend', 'by'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [9177, 9178, 9205], False, False, False, True
https://www.britannica.com/topic/People-of-Freedom, 0.06896551724137931, ['the', 'of'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [274, 288], False, False, False, True
https://www.ukessays.com/essays/politics/is-the-democracy-bad-for-development-politics-essay.php, 0.06896551724137931, ['to', 'by'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [2455, 2459], False, False, False, True
https://www.merriam-webster.com/dictionary/democratic%20socialism, 0.06896551724137931, ['the', 'of'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1994, 1998], False, False, False, True
https://www.lewrockwell.com/2012/04/frank-karsten/u2018democracy-cant-be-fixed-itsinherentlybroken/, 0.06896551724137931, ['to', 'by'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1297, 1300], False, False, False, True
https://www.commondreams.org/further/2009/05/11/worlds-happiest-countries-social-democracies, 0.06896551724137931, ['people', 'like'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [1970, 1971], False, False, False, True
https://www.truthdig.com/articles/how-swedish-socialism-failed/, 0.06896551724137931, ['the', 'of'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [330, 332], False, False, False, True
http://www.greenbeltmovement.org/wangari-maathai/key-speeches-and-articles/bottleknecks-to-development-in-africa, 0.06896551724137931, ['of', 'countries'], "allow me to defend democraticsociallsml by the livelihood of countries that in no waysocial.democracies, actually have decentralizei governments and free markets have elected people like me they're not socialist ", [7392, 7402], False, False, False, True
