--------------------------------------------------
Identified names are: hillary clinton
--------------------------------------------------
--------------------------------------------------
Query string is: hillary clinton i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton is ne for bij it
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton at the past
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton just ignore facts i'm a democrat so i'm awesome i elude o epa
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): IncompleteRead(65536 bytes read)
https://www.newsbusters.org/blogs/nb/curtis-houck/2016/07/13/maher-covers-hillary-e-mails-she-needed-private-server-get-her-work, 0.16666666666666666, ['is', 'for', 'it.', 'at', 'the', 'a', 'i'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1983, 2005, 2020, 2024, 2043, 2049, 2053], False, False, False, True
https://twitter.com/HillaryClinton/status/1128320182194192384, 0.11904761904761904, ['i', 'for', "women's", 'the', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [275, 283, 293, 312, 322], False, False, True, True
https://www.reddit.com/r/hillaryclinton/comments/5ejwox/america_where_a_woman_can_win_by_2_million_votes/, 0.11904761904761904, ['is', 'for', 'at', 'the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [10162, 10203, 10211, 10226, 10231], False, False, False, True
https://www.mrctv.org/blog/10-scandals-involving-hillary-clinton-you-may-have-forgotten, 0.09523809523809523, ['and', 'from', 'the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1660, 1669, 1730, 1733], False, False, False, True
https://www.columbiaspectator.com/news/2019/01/07/hillary-clinton-cuomo-call-for-decriminalization-of-abortion-in-new-york-at-rally-at-barnard/, 0.09523809523809523, ['also', 'the', 'at', 'work'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1185, 1191, 1219, 1256], False, False, False, True
https://www.opensecrets.org/pres16/contributors?cycle=2016&id=N00000019, 0.09523809523809523, ['money', 'from', 'the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1493, 1495, 1496, 1510], False, False, False, True
https://www.politifact.com/truth-o-meter/article/2016/feb/15/whos-blame-flint-water-crisis/, 0.09523809523809523, ['is', 'for', 'at', 'the'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3386, 3423, 3442, 3444], False, True, False, True
https://www.waynedupree.com/hillarys-law-license-reinstated-after-17-years/, 0.09523809523809523, ['from', 'also', 'the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1226, 1230, 1296, 1298], False, False, False, True
https://matadornetwork.com/pulse/im-black-woman-heres-just-cant-support-hillary-clinton/, 0.09523809523809523, ['for', 'at', 'the', 'past.'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4123, 4130, 4145, 4146], False, False, False, True
https://www.good.is/articles/hillary-clinton-speech-young-women-politics, 0.09523809523809523, ['the', 'at', 'is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3120, 3155, 3196, 3203], False, False, False, True
https://www.salon.com/2018/08/10/give-hillary-credit-clinton-didnt-win-but-she-inspired-a-sea-change-for-women-candidates/, 0.09523809523809523, ['for', 'and', 'from', 'the'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2155, 2159, 2197, 2230], False, False, False, True
https://www.washingtontimes.com/news/2016/jun/19/hillary-clintons-long-list-of-lies/, 0.09523809523809523, ['the', 'past.', 'just', 'a'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4460, 4475, 4537, 4538], False, False, False, True
https://www.foxbusiness.com/features/does-hillary-clinton-deserve-to-be-indicted-for-indiscretions, 0.09523809523809523, ['the', 'worn', 'at', 'is'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3145, 3152, 3177, 3191], False, False, False, True
https://www.theatlantic.com/politics/archive/2016/06/hillary-clintons-truth-problem/486395/, 0.09523809523809523, ['the', 'a', 'so', 'i'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5012, 5041, 5085, 5093], False, False, False, True
https://thepoliticalinsider.com/hillary-bill-in-the-past-weinstein/, 0.09523809523809523, ['i', 'for', 'right', 'and'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4682, 4688, 4692, 4752], False, False, False, True
https://preview.msn.com/en-us/sports/other/how-bill-clintons-past-is-impacting-hillarys-campaign/vi-BBo40cw, 0.09523809523809523, ['the', "i'm", 'a', "i'm"], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4144, 4187, 4203, 4215], False, False, False, True
https://www.wnd.com/2015/05/here-they-are-hillarys-22-biggest-scandals-ever/, 0.09523809523809523, ['is', 'for', 'at', 'the'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [11502, 11515, 11528, 11529], False, False, False, True
https://www.washingtonpost.com/news/the-fix/wp/2014/02/10/hillary-clintons-past-problem/, 0.09523809523809523, ['at', 'the', 'a', 'so'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2012, 2078, 2093, 2096], False, False, False, True
https://slate.com/human-interest/2016/11/a-lament-for-hillary-clinton-the-woman-on-election-night.html, 0.09523809523809523, ['the', 'work', 'is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [8552, 8571, 8577, 8613], False, False, False, True
https://www.scribd.com/document/388476763/Pandoras-Box-II-The-Denver-International-Airport-Story-by-Alex-Christopher, 0.09523809523809523, ['i', 'for', 'and', 'from'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1487, 1499, 1511, 1534], False, False, False, False
http://content.time.com/time/specials/packages/article/0,28804,2029774_2029776_2031827,00.html, 0.07142857142857142, ['also', 'the', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1073, 1087, 1105], False, False, False, True
https://madworldnews.com/hillary-lesbian-past-exposed/, 0.07142857142857142, ['and', 'from', 'also'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2195, 2203, 2214], False, False, False, True
https://www.foxnews.com/entertainment/bernie-sanders-tells-the-view-he-doesnt-need-advice-from-hillary-clinton-we-have-differences, 0.07142857142857142, ['the', 'a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2864, 2881, 2890], False, False, False, True
https://hotair.com/archives/2017/10/13/hillary-trump-sexual-assaulter-allegations-bill-past/, 0.07142857142857142, ['for', 'the', "i'm"], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3416, 3425, 3438], False, False, False, True
https://conservativemedia.com/politics/former-aide-clintons-love-nothing-shut-go-away/, 0.07142857142857142, ['for', 'and', 'also'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1868, 1884, 1900], False, False, False, True
https://www.history.com/topics/first-ladies/hillary-rodham-clinton, 0.07142857142857142, ['for', 'and', 'from'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2089, 2103, 2125], False, True, False, True
https://hillaryspeeches.com/scheduled-events/, 0.07142857142857142, ['the', 'is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3790, 3806, 3810], False, False, False, True
https://www.nbcnews.com/politics/hillary-clinton, 0.07142857142857142, ['at', 'for', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2202, 2247, 2265], False, False, False, True
https://www.youtube.com/watch?v=OSDDBysX-Nw, 0.07142857142857142, ['the', 'is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2734, 2749, 2805], False, False, False, True
https://thepoliticalinsider.com/chuck-norris-exposes-a-dark-secret-from-hillary-clintons-past-whoa/, 0.07142857142857142, ['and', 'from', 'also'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4530, 4547, 4592], False, False, False, True
https://www.breitbart.com/politics/2017/01/02/18-major-scandals-obama-presidency/, 0.07142857142857142, ['at', 'the', 'facts'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2731, 2735, 2737], False, False, False, True
https://www.telegraph.co.uk/news/worldnews/barackobama/2964789/Hillary-Clinton-supporters-ignore-her-plea-to-back-Barack-Obama.html, 0.07142857142857142, ['the', 'a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2663, 2690, 2691], False, False, False, True
http://libertywriters.com/2017/09/insane-hillary-clinton-just-said-morning-proves-lost-mind/, 0.07142857142857142, ['at', 'the', 'a'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4780, 4789, 4811], False, False, False, True
https://thoughtcatalog.com/amy-glass/2014/01/the-womens-movement-is-about-approving-of-every-choice-a-woman-makes-no-matter-what/, 0.07142857142857142, ['the', 'at', 'work'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [6383, 6385, 6417], False, False, False, True
https://www.oakpark.com/News/Articles/9-6-2016/There-is-only-one-candidate-to-vote-\'for\'/, 0.07142857142857142, ['facts', 'a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4433, 4451, 4452], False, False, False, True
https://pjmedia.com/trending/2016/10/20/hillarys-security-detail-hated-her-so-much-that-they-laughed-when-she-fell-and-broke-her-arm/, 0.07142857142857142, ['and', 'the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3152, 3161, 3202], False, False, False, True
http://time.com/3739541/transcript-hillary-clinton-email-press-conference/, 0.07142857142857142, ['i', 'for', 'right'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4103, 4114, 4130], False, False, False, True
https://pjmedia.com/trending/hillary-clinton-is-whistling-past-the-graveyard-with-impeachment-talk/, 0.07142857142857142, ['the', 'is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3947, 3958, 3984], False, False, False, True
https://www.glamour.com/story/on-the-cls-girlfriend-plea-of, 0.07142857142857142, ['the', 'at', 'is'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3811, 3814, 3856], False, False, False, True
https://www.democraticunderground.com/discuss/duboard.php?az=view_all&address=132x1837428, 0.07142857142857142, ['the', 'just', 'a'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [8388, 8406, 8408], False, False, False, True
https://www.worldtribune.com/fbi-official-missing-hillary-clinton-emails-found-in-obama-white-house/, 0.07142857142857142, ['and', 'from', 'also'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3826, 3829, 3869], False, False, False, True
https://www.nationalmemo.com/hillary-clinton-jeb-bush-and-ignoring-the-past/, 0.07142857142857142, ['also', 'the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5973, 5989, 6014], False, False, False, True
https://www.washingtonpost.com/archive/lifestyle/1993/12/28/bill-clintons-great-skivvies-give-away/0dac853d-cf3d-4faf-8104-bcf124bd93b4/, 0.07142857142857142, ['the', 'at', 'is'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1970, 1981, 1996], False, False, False, True
https://www.reddit.com/r/politics/comments/91260a/hillary_clinton_to_help_with_travel_arrangements/, 0.07142857142857142, ['the', 'just', 'ignore'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [10813, 10820, 10821], False, False, False, True
https://theconservativetreehouse.com/2016/09/07/example-254418-why-polling-news-is-just-well-silly/, 0.07142857142857142, ['at', 'the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [11033, 11036, 11051], False, False, False, True
https://www.rollingstone.com/politics/politics-news/hillary-clinton-for-president-118261/, 0.07142857142857142, ['the', 'a', 'so'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [21808, 21827, 21829], False, False, False, True
https://www.omaha.com/news/politics/hillary-clinton-plans-to-visit-omaha-on-monday/article_f457fefa-5419-11e6-b12d-83f1f903cfbc.html, 0.07142857142857142, ['and', 'from', 'the'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [16172, 16176, 16179], False, False, False, True
https://www.reddit.com/r/hillaryclinton/comments/5dwep9/calling_out_bernie_on_his_hypocrisy_and_how_it/, 0.07142857142857142, ['the', 'just', 'ignore'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [17098, 17111, 17112], False, False, False, True
https://theconservativetreehouse.com/2015/04/29/hillary-clinton-unmistakable-and-undeniable-racist-police-intentionally-killing-black-men/, 0.07142857142857142, ['at', 'the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [13166, 13192, 13203], False, False, False, True
https://reason.com/2015/08/12/hillary-clinton-keeps-making-untrue-clai, 0.07142857142857142, ['and', 'from', 'also'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [11290, 11306, 11320], False, False, False, True
https://politics.theonion.com/clinton-reminds-new-yorkers-she-moved-there-hoping-care-1819578809, 0.07142857142857142, ['also', 'the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [20107, 20176, 20186], False, False, False, True
http://acecomments.mu.nu/?post=371251, 0.07142857142857142, ['the', 'just', 'ignore'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [29856, 29920, 29923], False, False, False, True
http://www.returnofkings.com/83733/why-a-hillary-clinton-presidency-would-destroy-the-united-states, 0.07142857142857142, ['at', 'the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [25975, 26011, 26025], False, False, False, True
http://www.akdart.com/lib13.html, 0.07142857142857142, ['the', 'at', 'work'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [39078, 39082, 39101], False, False, False, True
https://www.hillaryclinton.com/, 0.047619047619047616, ['the', 'a'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [614, 641], False, False, False, True
https://www.npr.org/2016/05/08/477223957/clinton-must-clarify-her-economic-message-to-win-primary, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1986, 1990], False, False, False, True
https://www.politico.com/story/2015/06/hillary-clinton-didnt-turn-over-all-libya-emails-state-119453, 0.047619047619047616, ['the', 'is'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2210, 2226], False, False, False, True
https://bijog.com/article/private-planes-2016-presidential-candidates, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1011, 1037], False, False, False, True
https://thefederalist.com/2019/03/28/campaign-colluded-russians-2016-hillary-clintons/, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2296, 2301], False, False, False, True
https://www.mediaboss.net/hillary-clinton-2/hillary-clinton-warns-2020-democratic-candidates-of-stolen.php, 0.047619047619047616, ['the', 'is'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [958, 971], False, False, False, True
https://www.politico.com/news/hillary-clinton, 0.047619047619047616, ['and', 'from'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1131, 1133], False, False, False, True
https://www.washingtontimes.com/news/2019/may/16/hillary-clinton-thanks-planned-parenthood-for-figh/, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4893, 4899], False, False, False, True
https://twitter.com/hillaryclinton/status/971776610612449280, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1698, 1701], False, False, True, True
https://www.wbal.com/article/197867/109/hillary-clinton-leads-donald-trump-in-abc-news-electoral-ratings-before-tough-battleground-contests, 0.047619047619047616, ['a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2979, 2980], False, False, False, True
https://www.propublica.org/article/the-best-reporting-on-hillary-clinton-over-the-years, 0.047619047619047616, ['money', 'from'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4800, 4801], False, False, False, True
https://www.washingtontimes.com/news/2019/apr/22/barack-obama-hillary-clinton-tip-anti-christian-ea/, 0.047619047619047616, ['for', 'and'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1160, 1174], False, False, False, True
https://www.marketwatch.com/story/all-the-terrible-things-hillary-clinton-has-done-in-one-big-list-2016-02-04, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3694, 3703], False, False, False, True
https://www.charismanews.com/politics/elections/59341-is-hillary-clinton-too-sick-to-be-president-this-is-disturbing, 0.047619047619047616, ['the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2701, 2715], False, False, False, True
https://www.thesun.co.uk/news/2010921/former-security-guard-for-hillary-clinton-reveals-she-was-so-hated-by-staff-they-laughed-when-she-broke-her-elbow/, 0.047619047619047616, ['for', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2979, 2994], False, False, False, True
https://spectator.org/chelsea-clinton-superstar-and-also-every-woman/, 0.047619047619047616, ['the', 'is'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3844, 3856], False, False, False, True
https://www.chicagotribune.com/news/local/politics/ct-hillary-clinton-flint-water-immoral-20160207-story.html, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4095, 4097], False, False, False, True
https://www.theatlantic.com/politics/archive/2016/04/more-than-just-a-symbol/476490/, 0.047619047619047616, ['the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5968, 5973], False, False, False, True
https://www.latimes.com/nation/politics/la-na-clintons-future-20150422-story.html, 0.047619047619047616, ['a', 'so'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4591, 4596], False, False, False, True
https://www.theatlantic.com/politics/archive/2016/11/tracking-the-clinton-controversies-from-whitewater-to-benghazi/396182/, 0.047619047619047616, ['money', 'from'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5995, 5996], False, False, False, True
https://www.straitstimes.com/world/united-states/hillary-clinton-china-if-youre-listening-why-dont-you-get-trumps-tax-returns, 0.047619047619047616, ['the', 'a'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5737, 5752], False, False, False, True
https://www.youtube.com/watch?v=O32_IjK-BdM, 0.047619047619047616, ['and', 'the'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3305, 3317], False, False, False, True
https://redflagsocialistblog.wordpress.com/tag/barack-obama/page/2/, 0.047619047619047616, ['the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [4078, 4098], False, False, False, True
https://thehill.com/blogs/in-the-know/in-the-know/241872-ne-yo-hillary-clinton-is-a-favorite-of-mine-in-2016, 0.047619047619047616, ['for', 'and'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3462, 3468], False, False, False, True
https://thehill.com/homenews/campaign/413572-hillary-clinton-leaves-door-open-for-2020-run-id-like-to-be-president, 0.047619047619047616, ['for', 'and'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3855, 3897], False, False, False, True
https://www.youtube.com/watch?v=kypl1MYuKDY, 0.047619047619047616, ['at', 'is'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3826, 3846], False, False, False, True
https://apnews.com/82df550e1ec646098b434f7d5771f625, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3907, 3914], False, False, False, True
https://neonnettle.com/features/1453-cia-agent-hillary-clinton-involved-in-biggest-treason-in-us-history-, 0.047619047619047616, ['for', 'and'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1725, 1757], False, False, False, True
https://www.facebook.com/hillaryclinton/photos/pb.889307941125736.-2207520000.1556650850/2435979099791938/?type=3&eid=ARBeDTAX28NE1uT0IjoCi6EY4mbxd8we4QtjTnTp5BIjWS0csg4gwgSbNMPw_JyXibZS505EvSzCacLS, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2503, 2509], False, False, False, True
https://www.newsweek.com/hillary-clinton-women-problem-explained-369153, 0.047619047619047616, ['the', 'a'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5438, 5450], False, False, False, True
https://www.britannica.com/biography/Hillary-Clinton, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5549, 5582], False, False, False, True
https://www.facebook.com/hillaryclinton/photos/pb.889307941125736.-2207520000.1555310691/2394800393909809/?type=3&eid=ARDeUw6OPzYNUxxk8EUCIcRhoV3g4Yn1QIHwmrJQugl1u79ECx1N0ARBIj6hkRCdnUiGS8W1srZXtm5O, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3716, 3720], False, False, False, True
https://www.nytimes.com/2016/07/29/magazine/what-women-owe-hillary-clinton.html, 0.047619047619047616, ['for', 'it.'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5534, 5540], False, False, False, True
http://www.oilempire.us/cement.html, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [5778, 5785], False, False, False, True
https://www.usatoday.com/news/onpolitics/, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [10543, 10546], False, False, False, True
https://www.nytimes.com/2016/07/07/us/hillary-clinton-james-comey-emails.html, 0.047619047619047616, ['at', 'the'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [8476, 8477], False, False, False, True
https://www.washingtonpost.com/news/worldviews/wp/2016/10/19/the-story-behind-president-obamas-half-brother-malik-who-trump-invited-to-tonights-debate/, 0.047619047619047616, ['and', 'from'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [1614, 1621], False, False, False, True
https://www.reddit.com/r/politics/comments/bjtne1/hillary_clinton_im_living_rent_free_inside_of/, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [10522, 10526], False, False, False, True
https://patriotpulse.net/one-question-about-brett-kavanaugh-destroyed-chelsea-clinton/, 0.047619047619047616, ['and', 'money'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [2827, 2833], False, False, False, True
https://www.thedailybeast.com/the-view-presses-hillary-clinton-why-focus-on-the-past, 0.047619047619047616, ['i', 'e'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [12743, 12755], False, False, False, True
https://newrepublic.com/minutes/138595/hillary-clinton-inner-circle-holding-hope-even-no-one-else-is, 0.047619047619047616, ['for', 'right'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [8187, 8189], False, False, False, True
https://wattsupwiththat.com/2017/09/11/hillary-clinton-threatening-coal-jobs-was-a-mistake/, 0.047619047619047616, ['a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [9765, 9767], False, False, False, True
http://www.startribune.com/hillary-clinton-and-the-woman-card-in-a-stacked-deck/382161101/, 0.047619047619047616, ['male', 'counterparts.'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [8958, 8959], False, False, False, True
https://www.theguardian.com/us-news/2016/may/23/women-female-voters-us-election-hillary-clinton, 0.047619047619047616, ['male', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [16511, 16517], False, False, False, True
https://reason.com/blog/2015/08/18/hillary-clinton-too-important-to-make-an, 0.047619047619047616, ['a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [15753, 15755], False, False, False, True
https://www.theguardian.com/commentisfree/2014/oct/16/hillary-clinton-glass-ceiling-female-candidates, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [15845, 15853], False, False, False, True
https://journalstar.com/gallery/news/photos-hillary-clinton-in-nebraska/collection_fba07887-fea2-563c-829c-bb052ebbbcfc.html, 0.047619047619047616, ['the', 'a'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [17869, 17881], False, False, False, True
https://thehornnews.com/clinton-linked-massive-kickback-scheme/, 0.047619047619047616, ['a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [15508, 15509], False, False, False, True
https://www.pinterest.com/es35design/hillary-clinton/, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [19511, 19512], False, False, False, True
https://journalstar.com/gallery/news/photos-hillary-clinton-campaigns-in-nebraska/collection_b6de125a-0573-5945-9e6b-d69d40adeeaf.html, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [19403, 19412], False, False, False, True
https://en.wikipedia.org/wiki/Hillary_Clinton_presidential_campaign,_2016, 0.047619047619047616, ['and', 'money'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [10397, 10404], False, True, False, True
https://www.pinterest.com/desertraye/who-is-the-real-hillary-clinton/, 0.047619047619047616, ['i', 'e'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [3723, 3725], False, False, False, True
https://www.cnn.com/2017/06/01/politics/hillary-clinton-2016/index.html, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [29764, 29772], False, False, False, True
https://www.celebitchy.com/548641/hillary_clinton_i_am_proud_to_be_a_democrat_and_i_wish_bernie_were_too/, 0.047619047619047616, ['a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [27834, 27836], False, True, False, True
https://www.hillaryis44.org/2016/11/17/why-hillaryclintons-hillary2016-deserved-to-lose-why-realdonaldtrump-deserved-to-win/, 0.047619047619047616, ['is', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [22664, 22672], False, False, False, True
https://www.vulture.com/2019/04/review-metcalf-and-lithgow-in-hillary-and-clinton.html, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [19701, 19716], False, False, False, True
https://www.savingcountrymusic.com/the-last-thing-we-needs-is-country-stars-to-get-political-a-response/, 0.047619047619047616, ['a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [28828, 28829], False, False, False, True
https://www.cbsnews.com/news/democratic-convention/, 0.047619047619047616, ['a', 'democrat'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [31257, 31259], False, False, False, True
https://jonathanturley.org/2017/07/11/new-york-times-trump-jr-told-in-advance-that-anti-clinton-information-was-coming-from-russian-government-to-help-his-dad/, 0.047619047619047616, ['i', 'e'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [10142, 10147], False, False, False, True
https://democraticunderground.com/100211139730, 0.047619047619047616, ['i', 'for'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [14560, 14564], False, False, False, True
https://www.hillaryis44.org/2014/01/16/how-to-destroy-hillary-clinton-2016-part-i/, 0.047619047619047616, ['the', 'at'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [18085, 18087], False, False, False, True
https://en.wikipedia.org/wiki/Political_positions_of_Hillary_Clinton, 0.047619047619047616, ['a', 'so'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [37304, 37348], False, True, False, True
https://en.wikipedia.org/wiki/Hilary_Clinton, 0.047619047619047616, ['the', 'just'], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [30029, 30035], False, True, False, True
https://www.1011now.com/content/news/Hillary-Clinton-due-in-Omaha-Monday-388788262.html, 0.0, [], "i window e for women's right and accept money from jhosehat opprss also the worn at work ihan ihelr male counterparts. is ne for bij it. at the past. just ignore facts i'm a democrat so i'm awesome i elude o epa ", [], False, False, False, True
