--------------------------------------------------
Identified names are: hillary clinton
--------------------------------------------------
--------------------------------------------------
Query string is: hillary clinton want me to come to your universityand speak about income sure..
--------------------------------------------------


--------------------------------------------------
Query string is: hillary clinton ityllonly cost you 215,000 politifake.org
--------------------------------------------------


https://www.politifact.com/, 0.1875, ['to', 'to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [3543, 3572, 3573], False, True, False, False
https://religionnews.com/2016/07/18/hillary-clinton-needs-to-reach-out-to-nonreligious-americans/, 0.1875, ['to', 'to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [7715, 7736, 7737], False, False, False, True
https://thefederalistpapers.org/us/hillarys-plan-bring-in-one-million-muslim-refugees-in-first-term, 0.1875, ['to', 'about', 'cost'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [4031, 4044, 4053], False, False, False, True
https://www.politico.com/magazine/story/2015/09/carly-fiorina-debate-hillary-clintons-greatest-accomplishment-213157, 0.1875, ['to', 'to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [2359, 2369, 2382], False, False, False, True
https://www.montgomeryadvertiser.com/story/news/2019/03/03/cory-booker-hillary-clinton-speak-selma-alabama-annual-bloody-sunday-service/3007050002/, 0.1875, ['to', 'speak', 'about'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [21395, 21420, 21423], False, False, False, True
https://www.newsweek.com/hillary-clinton-wikileaks-wall-street-podesta-goldman-sachs-trade-middle-class-509297, 0.1875, ['me', 'to', 'come'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [4746, 4747, 4748], False, False, False, True
http://nymag.com/intelligencer/2013/07/hillary-clinton-is-a-very-well-paid-speaker.html, 0.1875, ['to', 'to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [23201, 23218, 23223], False, False, False, True
https://www.hillaryclinton.com/, 0.125, ['to', 'about'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [613, 633], False, False, False, True
https://www.hillaryclinton.com/issues/college/, 0.125, ['to', 'income'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [707, 728], False, False, False, True
https://www.dailywire.com/news/6981/5-things-secret-service-agents-have-revealed-about-aaron-bandler, 0.125, ['to', 'come'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [1174, 1201], False, False, False, True
https://www.politifact.com/truth-o-meter/rulings/pants-fire/, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [2855, 2856], False, True, False, True
https://yellowhammernews.com/hillary-clinton-to-receive-international-unity-award-at-annual-selma-march/, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [1812, 1814], False, False, False, True
https://www.snopes.com/fact-check/hillary-clinton-armani-jacket/, 0.125, ['to', 'to'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [82, 89], False, True, False, True
https://www.davemanuel.com/, 0.125, ['to', 'about'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [776, 780], False, False, False, True
http://politicalticker.blogs.cnn.com/2011/07/11/clinton-surpasses-75-million-in-speech-income-after-lucrative-2010/, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [4087, 4089], False, False, False, True
https://pjmedia.com/trending/let-hillary-speak/, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [3242, 3271], False, False, False, True
http://time.com/4355797/hillary-clinton-donald-trump-foreign-policy-speech-transcript/, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [8229, 8233], False, False, False, True
http://fortune.com/2016/11/09/hillary-clinton-concession-speech-transcript/, 0.125, ['to', 'come'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [5204, 5205], False, False, False, True
https://thefederalistpapers.org/us/why-government-is-not-your-friend-summed-up-in-17-words, 0.125, ['about', 'cost'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [4131, 4140], False, False, False, True
https://www.truthrevolt.org/news/hillarys-free-college-failure-plan-tax-rich-comes-billions-short, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [490, 492], False, False, False, True
https://www.politico.com/story/2016/02/clinton-speeches-218969, 0.125, ['to', 'to'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [3017, 3032], False, False, False, True
http://america.aljazeera.com/opinions/2014/6/hillary-bill-clintonwealthspeakerfees.html, 0.125, ['to', 'to'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [2412, 2425], False, False, False, True
http://fortune.com/2016/07/12/transcript-bernie-sanders-endorsement/, 0.125, ['come', 'to'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [4156, 4166], False, False, False, True
http://www.msnbc.com/msnbc/hillary-clinton-stumbles-money-questions, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [1172, 1179], False, False, False, True
https://www.christianpost.com/news/hillary-clintons-foundry-united-methodist-sermon-we-all-have-different-gifts.html, 0.125, ['to', 'come'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [3644, 3654], False, False, False, True
https://2009-2017.state.gov/secretary/20092013clinton/rm/2010/01/135519.htm, 0.125, ['to', 'come'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [6986, 6987], False, False, False, True
https://www.theguardian.com/us-news/2017/sep/25/white-women-husbands-voting, 0.125, ['to', 'speak'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [17376, 17380], False, False, False, True
https://www.foxnews.com/opinion/its-trump-or-the-end-of-the-america-we-know-and-love, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [1812, 1833], False, False, False, True
http://thepeoplescube.com/peoples-blog/politifake-org-the-thief-among-us-t4992.html, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [10376, 10387], False, False, False, True
https://www.huffingtonpost.com/entry/hillary-clinton-donald-trump-foundation-speaking-fees_us_56d0b8dee4b03260bf76d186, 0.125, ['your', 'speak'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [3659, 3666], False, False, False, True
https://news.yahoo.com/hillary-clinton-saul-alinsky-letters-155526953.html, 0.125, ['about', 'you'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [13292, 13297], False, False, False, True
https://www.sun-sentinel.com/news/politics/fl-obama-clinton-miami-gardens-20161020-story.html, 0.125, ['to', 'come'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [1189, 1190], False, False, False, True
https://www.cnbc.com/2017/05/28/hillary-clintons-2017-commencement-speech-at-wellesley.html, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [7990, 7992], False, False, False, True
https://www.rushlimbaugh.com/daily/2015/05/15/really_you_re_just_figuring_all_this_out_about_george_stephanopoulos/, 0.125, ['to', 'your'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [8338, 8339], False, False, False, True
https://en.wikipedia.org/wiki/Ronald_Kessler, 0.125, ['to', 'about'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [7802, 7813], False, False, False, True
https://en.wikipedia.org/wiki/Hillary_Rodham_Clinton, 0.125, ['to', 'come'], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [44941, 44942], False, True, False, True
https://www.judicialwatch.org/document-archive/richard-w-story-2004/, 0.0, [], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [], False, False, False, True
https://www.factcheck.org/2017/11/trumps-claims-dont-add/, 0.0, [], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [], False, False, False, True
https://legalinsurrection.com/2018/03/hillary-earned-less-for-college-speech-than-snooki-from-jersey-shore/, 0.0, [], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [], False, False, False, True
https://www.youtube.com/channel/UCupvZG-5ko_eiXAupbDfxWw, 0.0, [], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [], False, False, False, False
https://en.wikipedia.org/wiki/2017_Special_Counsel_investigation, 0.0, [], 'want me to come to your universityand speak about income sure... ityllonly cost you 215,000 politifake.org ', [], False, True, False, True
