--------------------------------------------------
Identified names are: john mccain
--------------------------------------------------
--------------------------------------------------
Query string is: john mccain anyone who picked sarah should maybe think twice before questioning other people's judgment
--------------------------------------------------


--------------------------------------------------
Query string is: john mccain just sayin'.
--------------------------------------------------


https://slatestarcodex.com/2018/08/27/elegy-for-john-mccain/, 0.2, ['think', 'twice', 'before'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [42362, 42363, 42364], False, False, False, True
https://gawker.com/5893652/meghan-mccain-poses-for-playboy-im-strictly-dickly, 0.13333333333333333, ['should', 'other'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [531, 548], False, False, False, True
https://www.democraticunderground.com/10029778038, 0.13333333333333333, ['who', 'sarah'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [1455, 1458], False, False, False, True
https://www.datalounge.com/thread/6945841-john-mccain-picked-sarah-palin-only, 0.13333333333333333, ['picked', 'sarah'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [726, 727], False, False, False, True
https://answers.yahoo.com/question/index?qid=20080518095337AASCTym, 0.13333333333333333, ['think', 'other'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [8112, 8132], False, False, False, True
http://www.watchblog.com/democrats/archives/006168.html, 0.13333333333333333, ['who', 'sarah'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [1597, 1612], False, False, False, True
https://uk.answers.yahoo.com/question/index?qid=20080920142936AA63oAt&sort=V, 0.13333333333333333, ['think', 'other'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [8684, 8704], False, False, False, True
https://www.huffingtonpost.com/phil-trounstine/im-just-sayin-beware-mcca_b_111102.html, 0.13333333333333333, ['before', 'other'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [4409, 4417], False, False, False, True
https://www.pantagraph.com/opinion/letters/trump-was-wrong-to-snub-mccain/article_acd234f7-f23d-5f8e-9b25-a55b7f6fc4b0.html, 0.13333333333333333, ['before', 'other'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [10187, 10212], False, False, False, True
https://www.cbsnews.com/news/becoming-one-with-mccain/, 0.13333333333333333, ['who', 'just'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [6692, 6722], False, False, False, True
https://blogs.chicagotribune.com/news_columnists_ezorn/2008/08/danielle-quayle.html, 0.13333333333333333, ['anyone', 'who'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [1657, 1658], False, False, False, True
https://www.ar15.com/forums/general/New-John-McCain-Pornography-tax-proposed-to-fund-the-border-wall/5-2187258/, 0.13333333333333333, ['who', 'should'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [8733, 8736], False, False, False, True
https://www.politicususa.com/2008/10/08/mccain-no-using-obama-middle-name.html, 0.13333333333333333, ['should', 'maybe'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [7820, 7821], False, True, False, True
https://www.politicususa.com/2008/08/31/kerry-palin-is-an-insult.html, 0.13333333333333333, ['who', 'sarah'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [11300, 11309], False, False, False, True
http://caffertyfile.blogs.cnn.com/2008/09/03/should-mccain-consider-replacing-palin/, 0.13333333333333333, ['anyone', 'who'], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [6274, 6275], False, False, False, True
https://www.datalounge.com/thread/7084046-four-of-the-last-5-presidents-have-been-left-handed, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.datalounge.com/thread/6430466-is-john-mccain-a-fag-hag-, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://thecaucus.blogs.nytimes.com/2008/09/06/sunday-breakfast-menu-sept-7/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
http://www.redpillsentinel.com/home/fyijohn-mccain-was-never-a-good-personjust-sayin, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.politico.com/story/2015/07/trump-attacks-mccain-i-like-people-who-werent-captured-120317, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
http://www.renewamerica.com/columns/huntwork/081222, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.tabletmag.com/jewish-news-and-politics/269538/john-mccains-reckless-love, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.politico.com/blogs/jonathanmartin/1008/The_Palin_story_goes_onand_on.html, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://werejustsayin.blogspot.com/2008/02/what-do-lobbyists-wear.html, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.pinterest.com/pin/439663982344163978/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.crossbownation.com/community/threads/just-sayin.82988/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://lucyinamerica.blogspot.com/#!, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, False
https://werejustsayin.blogspot.com/2018/08/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://johnrmccain.blogspot.com/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://iotwreport.com/mccains-last-words-were-perfect-it-showed-what-a-damn-liar-he-was-to-his-constituents/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://forums.plentyoffish.com/10754456datingPostpage50.aspx, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, True, False, True
https://answers.yahoo.com/question/index?qid=20080416042004AABb8Nm, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://arizonadailyindependent.com/2017/07/16/mccain-has-surgery-to-remove-blood-clot-recovering-at-home/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.politico.com/blogs/scorecard/0808/Alaska_Republicans_offer_frosty_reaction_to_Palin_pick.html, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.newser.com/story/204364/mccain-obama-get-over-israel-tantrum.html, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://reason.com/2008/09/03/sarah-palins-ripping-yarns, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, True, False, True
https://fellowshipoftheminds.com/did-john-mccain-really-die-from-brain-cancer, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.pantagraph.com/opinion/letters/mccain-s-death-a-loss-for-america/article_ae4f236c-9f91-51b0-8ae9-dc4d2db955ca.html, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://reason.com/archives/2008/09/03/sarah-palins-ripping-yarns, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, True, False, True
https://japantoday.com/category/world/palin-questions-mccains-concession-of-michigan, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://startthinkingright.wordpress.com/tag/john-mccain/page/3/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
http://www.floppingaces.net/most-wanted/sen-john-mccain-81/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], True, False, False, True
https://www.salina.com/news/20190322/just-sayin, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://mountainx.com/arts/art-news/edgy_mama_forget_sarah_palin_edgy_mama_for_vice_president/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
http://www.gopusa.com/meghan-mccain-unleashes-on-dinesh-dsouza-for-comments-on-dad/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://hubpages.com/politics/forum/7385/mccains-vp-choice, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.firstthings.com/blogs/firstthoughts/2009/11/rogue-thoughts-chapter-by-chapter-on-sarah-palin, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, True, False, True
https://theconservativetreehouse.com/2017/07/16/senator-john-mccain-undergoes-minimally-invasive-craniotomy/comment-page-2/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://frontpageconfidential.com/stains-of-john-mccain/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://en.wikipedia.org/wiki/United_States_presidential_election,_2008, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, True, False, True
http://caffertyfile.blogs.cnn.com/2008/09/24/why-won%e2%80%99t-mccain-camp-let-palin-talk-to-the-press/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.azcentral.com/story/news/politics/arizona/2018/05/16/5-takeaways-sen-john-mccains-new-memoir-restless-wave/600666002/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.wonkette.com/az-republican-kelli-ward-reminds-john-mccain-theres-no-i-have-brain-cancer-in-team, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
http://www.bradwarthen.com/2008/08/choosing-palin/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
https://www.disabledveterans.org/2017/07/20/turncoat-john-mccain-refuses-free-va-surgery-for-brain-tumor/, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, True, False, True
https://www.salina.com/opinion/20180517/john-mccain-is-regarded-highly-for-many-reasons, 0.0, [], "anyone who picked sarah should maybe think twice before questioning other people's judgment. just sayin'. ", [], False, False, False, True
