--------------------------------------------------
Identified names are: melania trump
--------------------------------------------------
--------------------------------------------------
Query string is: melania trump i also wake up every morning in a house built by slaves..
--------------------------------------------------


--------------------------------------------------
Query string is: melania trump oops....i mean...
--------------------------------------------------


--------------------------------------------------
Query string is: melania trump unpaid contractors....
--------------------------------------------------


EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): HTTP Error 403: Forbidden
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 286 "search_result_html = self.download_url(search_result_url)"): <urlopen error [Errno 104] Connection reset by peer>
http://time.com/4423176/democratic-convention-michelle-obama-star/, 0.5625, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [3694, 3695, 3696, 3697, 3698, 3699, 3700, 3703, 3704], False, False, False, True
http://iksplain.com/index.php/2016/07/26/michelle-obama-speech-democratic-national-convention-video/, 0.5625, ['also', 'wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [1682, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1703], False, False, False, True
https://www.youtube.com/watch?v=zHnJ2sTIVUI, 0.5625, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [1889, 1890, 1891, 1892, 1893, 1894, 1895, 1898, 1899], False, False, False, True
https://www.newser.com/story/228673/michelle-obama-when-they-go-low-we-go-high.html, 0.5625, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [3896, 3897, 3898, 3899, 3900, 3901, 3902, 3905, 3906], False, False, False, True
https://www.theurbanpolitico.com/2016/07/michelle-obama-reminds-america-about.html, 0.5625, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [7172, 7173, 7174, 7175, 7176, 7177, 7178, 7181, 7182], False, True, False, True
https://www.newsweek.com/michelle-obama-delivers-electric-endorsement-hillary-clinton-democratic-483858, 0.5625, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [4721, 4722, 4723, 4724, 4725, 4726, 4727, 4730, 4731], False, False, False, True
https://www.facebook.com/cnn/videos/10155084870026509/, 0.5625, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [1888, 1889, 1890, 1891, 1892, 1893, 1894, 1897, 1898], False, False, False, True
https://www.politifact.com/truth-o-meter/statements/2016/jul/25/michelle-obama/michelle-obama-correct-white-house-was-built-slave/, 0.5, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2547, 2548, 2549, 2550, 2551, 2552, 2553, 2559], False, True, False, True
https://www.indy100.com/article/the-sure-sign-donald-trump-knows-he-got-owned-by-michelle-obama--ZkSbWi3U8Z, 0.5, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2479, 2480, 2481, 2482, 2483, 2484, 2485, 2488], False, False, False, True
http://static1.businessinsider.com/r-an-obama-not-the-president-brings-down-the-house-at-democratic-convention-2016-7, 0.5, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2797, 2798, 2799, 2800, 2801, 2802, 2803, 2806], False, False, False, True
https://decker.com/blog/tag/melania-trump/, 0.5, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619], False, False, False, True
https://people.com/celebrity/michelle-obama-takes-on-donald-trump-at-dnc-expressed-support-for-clinton/#!, 0.5, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [6754, 6755, 6756, 6757, 6758, 6759, 6760, 6761], False, False, False, True
https://rickeysmileymorningshow.com/1698957/first-lady-michelle-obama-delivers-emotional-and-powerful-speech-supporting-hillary-clinton-video/, 0.5, ['wake', 'up', 'every', 'morning', 'in', 'a', 'house', 'built'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850], False, False, False, True
https://gossiponthis.com/2016/07/27/michelle-obama-remember-slaves-helped-build-white-house-nation-dnc-speech-video/, 0.3125, ['wake', 'up', 'every', 'morning', 'in'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [7126, 7127, 7128, 7129, 7130], False, False, False, True
https://twitter.com/jfreewright/status/757805189919145984, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [275, 276, 277, 278], False, False, False, True
https://www.thoughtco.com/funniest-melania-trump-memes-4064562, 0.25, ['also', 'wake', 'up', 'every'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [5908, 5909, 5910, 5911], True, False, False, True
http://static1.businessinsider.com/bill-oreilly-michelle-obama-white-house-slaves-2016-7, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2811, 2812, 2813, 2814], False, False, False, True
https://www.daytondailynews.com/news/national-govt--politics/fact-checking-michelle-obama-did-slaves-really-build-the-white-house/ENOQK7R5jci0iZJAlivGvJ/, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [5159, 5160, 5161, 5162], False, False, False, True
https://www.democracynow.org/2016/7/28/bill_o_reilly_claims_enslaved_africans, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2493, 2494, 2495, 2496], False, False, False, True
https://www.blackenterprise.com/michelle-obama-scrutinized-for-saying-white-house-was-built-by-slaves/, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2535, 2536, 2537, 2538], False, False, False, True
https://howafrica.com/6-historic-structures-america-built-slaves/, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [3096, 3097, 3098, 3099], False, False, False, True
https://www.cosmopolitan.com/politics/a8492455/15-times-you-were-totally-obsessed-with-michelle-obama-in-2016/, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [6225, 6226, 6227, 6228], False, False, False, True
https://www.theroot.com/6-historic-structures-in-america-that-were-built-by-sla-1790856172, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [21664, 21665, 21666, 21667], False, False, False, True
https://archive.is/qjktE, 0.25, ['wake', 'up', 'every', 'morning'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [6091, 6092, 6093, 6094], False, False, False, True
https://thehill.com/homenews/administration/442443-former-trump-adviser-says-she-was-thrown-under-the-bus-by, 0.1875, ['in', 'a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [3901, 3902, 3908], False, False, False, True
https://www.jlbe.com/melania-trump-spokeswoman-slams-first-ladys-former-adviser-stephanie-winston-wolkoff-she-ran-to-the-media-with-hurt-feelings-and-a-bruised-ego.html, 0.1875, ['in', 'a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [2289, 2293, 2301], False, False, False, True
https://www.timesunion.com/news/medical/article/Melania-Trump-to-announce-expansion-of-Be-Best-13825263.php, 0.1875, ['in', 'a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [7114, 7122, 7145], False, False, False, True
https://www.jsonline.com/story/news/politics/elections/2016/06/09/donald-trumps-trail-of-unpaid-bills/85685206/, 0.1875, ['in', 'a', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [9077, 9089, 9105], False, False, False, True
https://www.nbcnews.com/politics/donald-trump/melania-trump-calls-firing-top-national-security-aide-extraordinary-move-n935906, 0.1875, ['in', 'a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [5536, 5556, 5558], False, False, False, True
https://www.wonkette.com/bill-oreilly-slaves-who-built-white-house-had-it-great, 0.1875, ['house', 'built', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [43486, 43487, 43488], False, False, False, True
https://www.elitedaily.com/p/melania-trump-didnt-stand-up-when-trump-mentioned-family-faith-so-yikes-8071208, 0.125, ['a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [1537, 1539], False, False, False, True
https://www.usmagazine.com/celebrity-news/news/melania-trumps-nude-1995-modeling-pictures-surface-w431848/, 0.125, ['a', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [4684, 4694], False, False, False, True
https://en.wikipedia.org/wiki/Stephanie_Grisham, 0.125, ['a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [541, 569], False, False, False, True
https://www.joemygod.com/2019/05/trump-inaugural-aide-they-threw-me-under-the-bus/, 0.125, ['i', 'in'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [1389, 1396], False, False, False, True
http://static7.businessinsider.com/ap-melania-trump-says-white-house-could-mean-millions-for-brand-2017-2, 0.125, ['in', 'a'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [4830, 4855], False, False, False, True
https://www.someecards.com/news/politics/donald-trump-melania-ivanka-howard-stern/, 0.125, ['a', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [3721, 3736], False, False, False, True
https://www.youtube.com/watch?v=Hg9HmnsLzyk, 0.125, ['in', 'a'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [3704, 3707], False, False, False, True
https://www.wmagazine.com/story/melania-trump-ivanka-trump-state-of-the-union-suit-dress, 0.125, ['a', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [1647, 1663], False, False, False, True
https://thehill.com/homenews/media/433830-melania-trump-spokeswoman-tears-into-the-view-for-petty-mean-girl-spirit, 0.125, ['i', 'also'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [3907, 3917], False, False, False, True
https://www.bayoubuzz.com/dir/index.php/item/1061888-melania-trump-s-oops-speech-and-the-usual-trump-campaign-mode-response, 0.125, ['in', 'a'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [5589, 5614], False, False, False, True
https://www.usatoday.com/story/news/politics/elections/2016/06/09/donald-trump-unpaid-bills-republican-president-laswuits/85297274/, 0.125, ['up', 'in'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [11647, 11660], False, False, False, True
https://www.therichest.com/world-entertainment/15-stunning-photos-of-a-young-melania-trump/, 0.125, ['in', 'a'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [5988, 5997], False, False, False, True
http://fortune.com/2018/06/22/melania-trump-jacket-zara-controversy-swastika-holocaust-clothing/, 0.125, ['a', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [7262, 7287], False, False, False, True
https://thepostglob.com/2019/05/07/report-she-ran-to-the-media-with-hurt-feelings-and-a-bruised-ego/, 0.125, ['a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [4273, 4281], False, False, False, True
https://www.nytimes.com/2019/05/06/us/politics/trump-inauguration-stephanie-winston-wolkoff.html, 0.125, ['house', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [7526, 7544], False, False, False, True
https://www.newsweek.com/what-does-be-best-mean-melania-trump-913429, 0.125, ['every', 'in'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [7427, 7450], False, False, False, True
https://www.viportal.co/inaugural-official-disputes-white-house-account-of-her-departure/, 0.125, ['a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [6197, 6216], False, False, False, True
https://www.nytimes.com/2019/01/14/us/politics/trump-inauguration-spending.html, 0.125, ['a', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [8692, 8705], False, False, False, True
https://www.newsweek.com/fox-news-rips-fake-melania-trump-conspiracy-theory-view-jealousy-1361771, 0.125, ['every', 'in'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [7676, 7699], False, False, False, True
https://hollywoodlife.com/2018/12/28/melania-trump-nude-leggings-pants/, 0.125, ['a', 'house'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [5472, 5490], False, False, False, True
https://www.thedailybeast.com/sorry-melania-trumps-pussy-bow-blouse-doesnt-mean-anything, 0.125, ['a', 'by'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [16741, 16763], False, False, False, True
https://sports.yahoo.com/off-tone-melania-trump-tweet-202914517.html, 0.125, ['in', 'a'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [15142, 15163], False, False, False, True
https://www.theonion.com/the-donald-trump-in-these-allegations-is-not-the-comple-1819585039, 0.125, ['wake', 'up'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [21937, 21938], False, False, False, True
https://theslot.jezebel.com/vanity-fairs-big-mean-spirited-melania-story-is-here-1794545848, 0.125, ['in', 'a'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [23594, 23609], False, False, False, True
https://news.google.com/topics/CAAqKAgKIiJDQkFTRXdvTkwyY3ZNVEZqTW1vM09UQm9laElDWlc0b0FBUAE, 0.125, ['in', 'a'], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [33800, 33814], False, False, False, True
https://www.bloomberg.com/news/articles/2017-01-05/trump-s-dc-hotel-tagged-with-5-million-in-unpaid-worker-liens, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, False
https://www.palmerreport.com/analysis/melania-trump-problem-whole/15903/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.cheatsheet.com/health-fitness/melania-trump-does-everyday.html/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.cheatsheet.com/culture/the-most-shocking-scandals-about-melania-trump.html/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.snopes.com/fact-check/melania-trump-wore-pussy-bow/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, True, False, True
https://pressfrom.info/us/news/politics/-21271-electrical-contractor-suing-trump-hotel-for-2-million-in-unpaid-bill.html, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.nbcnews.com/news/us-news/electrical-contractor-suing-trump-hotel-2-million-unpaid-bill-n712131, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
http://fortune.com/2016/09/30/donald-trump-stiff-contractors/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.rawstory.com/2019/01/us-federal-contractors-fight-back-pay-shutdown/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.cheatsheet.com/money-career/revealing-details-you-need-to-know-about-melania-trumps-lawsuits.html/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.youtube.com/watch?v=NZcdUqnQFYg, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.wmagazine.com/story/donald-trump-jokes-melania-may-leave-white-house, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.dailykos.com/stories/2016/7/19/1549704/-Melania-Trump-is-a-liar-like-her-husband-objectively, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://twitter.com/flotus, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, True, True
http://kwotable.com/2017/01/25/electrical-contractor-suing-trump-hotel-unpaid-2-million-bill/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
http://polipace.com/2018/01/23/melania-banned-secret-trump-bedroom-white-house/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://pressenquirer.com/84701/washington-state-lawsuit-says-contractor-work-went-unpaid/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
http://www.msnbc.com/topics/melania-trump, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://theconservativetreehouse.com/author/sundancecracker/page/9/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://nypost.com/2018/02/27/melania-trump-cuts-ties-with-pal-whose-firm-earned-26m-inauguration-payday/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.newsweek.com/melania-trump-winston-wolkoff-inauguaration-white-house-1417640, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.thedailybeast.com/jimmy-kimmel-calls-for-a-special-investigator-to-look-into-why-melania-despises-donald-trump, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://en.wikipedia.org/wiki/Melania_Trump, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://bipartisanreport.com/2019/04/29/cohen-freaks-out-over-going-to-prison-because-trump-banged-a-porn-star/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.usatoday.com/story/life/people/2019/03/12/melania-trumps-rep-the-view-body-double-jokes-sad-shameful/3142728002/, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.popdust.com/finally-the-reason-melania-trump-squints-1893091626.html, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
https://www.washingtonpost.com/politics/melania-trump-marks-the-first-anniversary-of-be-best/2019/05/07/1d17821a-70c9-11e9-9f06-5fc2ee80027a_story.html, 0.0, [], 'i also wake up every morning in a house built by slaves... oops....i mean.... unpaid contractors.... ', [], False, False, False, True
